import Link from "next/link";
import { SiteHeader } from "./site-header";
import { BrandIcon, BrandLogo } from "./brand";

type Step = {
  title: string;
  description: string;
};

type Faq = {
  question: string;
  answer: string;
};

export type AiSearchPageProps = {
  slug: string;
  eyebrow: string;
  title: string;
  intro: string;
  summary: string;
  status: string;
  steps: Step[];
  dataTitle: string;
  dataIntro: string;
  dataPoints: string[];
  prompts: string[];
  faqs: Faq[];
};

const guides = [
  { href: "/garmin-to-chatgpt", label: "Garmin to ChatGPT" },
  { href: "/garmin-to-claude", label: "Garmin to Claude" },
  { href: "/garmin-mcp", label: "Garmin MCP" },
  { href: "/wearable-mcp", label: "Wearable MCP" },
];

export default function AiSearchPage({
  slug,
  eyebrow,
  title,
  intro,
  summary,
  status,
  steps,
  dataTitle,
  dataIntro,
  dataPoints,
  prompts,
  faqs,
}: AiSearchPageProps) {
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        name: title,
        url: `https://trapeak.com/${slug}`,
        description: intro,
        isPartOf: { "@type": "WebSite", name: "TRAPEAK", url: "https://trapeak.com" },
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "TRAPEAK", item: "https://trapeak.com" },
          { "@type": "ListItem", position: 2, name: "AI guides", item: "https://trapeak.com/ai-guides" },
          { "@type": "ListItem", position: 3, name: eyebrow, item: `https://trapeak.com/${slug}` },
        ],
      },
      {
        "@type": "FAQPage",
        mainEntity: faqs.map(({ question, answer }) => ({
          "@type": "Question",
          name: question,
          acceptedAnswer: { "@type": "Answer", text: answer },
        })),
      },
    ],
  };

  return (
    <main className="guide-page">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <SiteHeader />

      <section className="guide-hero shell">
        <p className="guide-breadcrumb"><Link href="/">TRAPEAK</Link><span>/</span><Link href="/ai-guides">AI guides</Link><span>/</span><strong>{eyebrow}</strong></p>
        <div className="eyebrow"><span className="live-dot" /> {eyebrow}</div>
        <h1>{title}</h1>
        <div className="guide-hero-bottom">
          <p>{intro}</p>
          <div className="guide-status"><b>PRODUCT STATUS</b><span>IN DEVELOPMENT</span><p>{status}</p></div>
        </div>
      </section>

      <section className="guide-answer">
        <div className="shell guide-answer-grid">
          <p className="section-index">THE SHORT ANSWER</p>
          <h2>{summary}</h2>
        </div>
      </section>

      <section className="guide-section shell" id="how">
        <div className="guide-heading">
          <p className="section-index">HOW IT IS PLANNED TO WORK</p>
          <h2>From permission<br />to context.</h2>
        </div>
        <ol className="guide-steps">
          {steps.map((step, index) => (
            <li key={step.title}>
              <span>0{index + 1}</span>
              <div><h3>{step.title}</h3><p>{step.description}</p></div>
            </li>
          ))}
        </ol>
      </section>

      <section className="guide-data" id="data">
        <div className="shell guide-data-grid">
          <div><p className="section-index light">PLANNED DATA ACCESS</p><h2>{dataTitle}</h2><p>{dataIntro}</p></div>
          <ul>{dataPoints.map((point, index) => <li key={point}><span>0{index + 1}</span>{point}</li>)}</ul>
        </div>
      </section>

      <section className="guide-prompts shell">
        <div><p className="section-index">EXAMPLE QUESTIONS</p><h2>Ask in plain<br />language.</h2></div>
        <div className="prompt-list">
          {prompts.map((prompt) => <blockquote key={prompt}>“{prompt}”</blockquote>)}
          <small>Illustrative examples only. AI responses would be generated by the connected assistant using authorized data made available through TRAPEAK. Garmin is the first planned source, subject to approval.</small>
        </div>
      </section>

      <section className="faq shell guide-faq" id="faq">
        <p className="section-index">FAQ</p>
        <h2>Direct answers.</h2>
        {faqs.map(({ question, answer }) => (
          <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>
        ))}
      </section>

      <section className="guide-related">
        <div className="shell">
          <p className="section-index">RELATED GUIDES</p>
          <div className="related-grid">
            {guides.filter((guide) => guide.href !== `/${slug}`).map((guide) => (
              <Link href={guide.href} key={guide.href}><span>{guide.label}</span><b>↗</b></Link>
            ))}
          </div>
        </div>
      </section>

      <section className="final-cta">
        <div className="shell"><BrandIcon className="cta-brand-icon" size={70} /><h2>Follow the build.</h2><p>Join early access and hear when the first approved integration is available.</p><a className="button gradient" href="mailto:support@trapeak.com?subject=TRAPEAK%20early%20access">Join early access <span>↗</span></a></div>
      </section>

      <footer className="shell guide-footer">
        <div className="footer-brand"><Link className="wordmark" href="/" aria-label="TRAPEAK home"><BrandLogo /></Link><p>Fitness data infrastructure for AI.</p></div>
        <div><Link className="footer-heading-link" href="/ai-guides">AI GUIDES</Link>{guides.map((guide) => <Link href={guide.href} key={guide.href}>{guide.label}</Link>)}</div>
        <div><b>LEGAL</b><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Service</Link><Link href="/data-deletion">Data Deletion</Link></div>
        <div><b>CONTACT</b><a href="mailto:support@trapeak.com">support@trapeak.com</a></div>
        <p className="copyright">© 2026 TRAPEAK. Product in development. Garmin, ChatGPT, Claude, and other names and trademarks belong to their respective owners. References do not imply endorsement or partnership.</p>
      </footer>
    </main>
  );
}
