import type { Metadata } from "next";
import { LegalPage } from "../legal-page";

export const metadata: Metadata = { title: "Terms of Service", description: "Terms for using the TRAPEAK private-beta data layer, AI connections and delegated read-only access.", alternates: { canonical: "/terms" } };

export default function Terms() {
  return <LegalPage eyebrow="LEGAL / 02" title="Terms of Service">
    <p>These terms apply to trapeak.com and the limited beta TRAPEAK service. The operating legal entity, address, governing law, and final public account conditions will be published before general public availability.</p>
    <h2>1. Service purpose</h2><p>TRAPEAK provides a user-controlled data layer between supported fitness sources, records saved at the user’s request, compatible AI clients and registered people the user explicitly authorizes. Records may include workouts, nutrition, dated weight, profile context, medications and laboratory results. Beta functionality may change while the service is developed and tested.</p>
    <h2>2. AI output and no medical advice</h2><p>TRAPEAK transmits user-authorized data and does not itself generate AI answers, medical advice, diagnosis, treatment, or professional coaching advice. Output from a connected AI service is generated by that third party and may be incomplete or incorrect. Review important decisions independently.</p>
    <h2>3. Laboratory data</h2><p>Laboratory values, reference ranges, and flags are stored as reported by you or your connected AI client. TRAPEAK does not verify or interpret them as a diagnosis. Review laboratory results and health decisions with a qualified clinician.</p>
    <h2>4. Integrations</h2><p>Availability depends on technical readiness, client compatibility, and provider approval. Third-party services operate under their own terms. Their names and trademarks do not imply endorsement or partnership.</p>
    <h2>5. User-authorized connections and sharing</h2><p>You are responsible for the data sources and AI clients you connect, protecting credentials and reviewing third-party permissions and terms. You may grant another registered user temporary read-only access to selected Training, Nutrition or Health categories. Send invitation links only to the intended email recipient and revoke access when it is no longer needed. Disconnecting or revoking access does not necessarily delete data already received by that third party.</p>
    <h2>6. Acceptable use</h2><p>You may not misuse the service, attempt unauthorized access, access another person’s data, interfere with operation, introduce malicious code, or violate applicable law or third-party rights.</p>
    <h2>7. Intellectual property</h2><p>The TRAPEAK name, design, copy, and original website content are owned by or licensed to TRAPEAK. You may view the website for personal, non-commercial purposes but may not reproduce or distribute it without permission.</p>
    <h2>8. Availability and liability</h2><p>The beta service is provided “as is” and may be changed, suspended, or withdrawn. To the maximum extent permitted by law, we are not liable for indirect or consequential loss arising from beta functionality or output produced by third-party AI services.</p>
    <h2>9. Contact</h2><p>Questions may be sent to <a href="mailto:support@trapeak.com">support@trapeak.com</a>.</p>
  </LegalPage>;
}
