import type { AppLocale } from "./config";

export type UiMessages = Readonly<{
  common: {
    home: string; dashboard: string; how: string; examples: string; useCases: string;
    faq: string; menu: string; signIn: string; createAccount: string; earlyAccess: string;
    language: string; backHome: string; delete: string; unavailable: string; notRecorded: string;
    readGuide: string; privateBeta: string; contact: string; legal: string; privacy: string;
    terms: string; dataDeletion: string; copyright: string;
  };
  auth: {
    eyebrow: string; signInTitle: string; signInDescription: string; signInSetup: string;
    signUpTitle: string; signUpDescription: string; signUpSetup: string;
  };
  nav: {
    overview: string; training: string; nutrition: string; health: string;
    sharedAccess: string; connections: string; profile: string; accountData: string;
  };
  dashboard: {
    overview: string; title: string; intro: string; dataOverview: string;
    noWorkouts: string; workout: string; durationUnavailable: string; connectWahoo: string;
    activities7: string; openTraining: string; nutritionToday: string; nothingLogged: string;
    recordFood: string; openNutrition: string; noLabs: string; healthSeparate: string;
    openHealth: string; profileContext: string; goalsContext: string; updateWithAi: string;
    noGrants: string; shareByEmail: string; manageAccess: string; noWearable: string;
    workoutsStored: string; otherDataWithAi: string; manageConnections: string;
    boundaries: string; boundaryTitle: string; trainingDescription: string;
    nutritionDescription: string; healthDescription: string;
  };
  training: {
    title: string; intro: string; unavailable: string; unavailableHint: string; openConnections: string;
    last7: string; trainingTime: string; previous7: string; consecutive: string; activities: string;
    days: string; recent: string; completed: string; in28: string; noCompleted: string;
    activity: string; askAi: string; prompt: string; coverage: string; limitations: string;
  };
  nutrition: {
    title: string; intro: string; summary: string; today: string; kilocalories: string;
    protein: string; carbohydrates: string; latestWeight: string; noMeasurement: string;
    unavailable: string; unavailableHint: string; history: string; byDay: string;
    recentEntries: string; noRecords: string; example: string; entries: string;
    openDetails: string; estimated: string; assumptions: string; recordNaturally: string;
    recordHint: string; confirmDelete: string;
  };
  health: {
    title: string; intro: string; laboratory: string; reports: string; unavailable: string;
    noReports: string; saveHint: string; collected: string; results: string; conditions: string;
    noConditions: string; injuries: string; noInjuries: string; contraindications: string;
    noContraindications: string; medications: string; noMedications: string; detailsMissing: string;
    adviceTitle: string; advice: string; confirmDelete: string;
  };
  connections: {
    title: string; intro: string; available: string; connected: string; reconnect: string;
    notConnected: string; connectedAs: string; storedWorkouts: string; lastSync: string;
    automatic: string; enabled: string; manual: string; notAvailable: string; sync: string;
    disconnect: string; expired: string; import: string; connect: string; storageMissing: string;
    roadmap: string; planned: string; noRecovery: string;
  };
  access: {
    eyebrow: string; title: string; intro: string; newInvitation: string; chooseShare: string;
    readonlyNotice: string; rules: string; rule1: string; rule2: string; rule3: string;
    outgoing: string; peopleAccess: string; total: string; none: string; incoming: string;
    sharedWithYou: string; active: string; noneIncoming: string; sharedUser: string;
    expires: string; activity: string; events: string; noneEvents: string; training: string;
    nutrition: string; health: string; recoveryLegacy: string; email: string; categories: string;
    trainingDescription: string; nutritionDescription: string; healthDescription: string;
    recoveryDescription: string; healthWarning: string; period: string; days7: string;
    days30: string; days90: string; year1: string; creating: string; create: string;
    invitationError: string; invitationLink: string; linkHint: string; revoking: string;
    revoke: string; invitationEyebrow: string; invitationTitle: string; invitationIntro: string;
    accepting: string; accept: string; rejecting: string; reject: string; responseError: string;
  };
  profile: {
    eyebrow: string; title: string; intro: string; interface: string; interfaceHint: string;
    language: string; timeZone: string; timeZoneHint: string; measurement: string;
    measurementHint: string; metric: string; imperial: string; save: string; saving: string;
    saved: string; error: string; independence: string; independenceText: string;
  };
  status: {
    connected: string; disconnected: string; denied: string; invalidState: string;
    alreadyLinked: string; error: string; disconnectError: string; notConnected: string;
    reconnectRequired: string; syncError: string; syncSuccess: string;
  };
}>;

const en: UiMessages = {
  common: { home: "Home", dashboard: "Dashboard", how: "How it works", examples: "Examples", useCases: "Use cases", faq: "FAQ", menu: "Menu", signIn: "Sign in", createAccount: "Create account", earlyAccess: "Join early access", language: "Language", backHome: "Back to TRAPEAK", delete: "Delete", unavailable: "Unavailable", notRecorded: "Not recorded", readGuide: "Read the guide →", privateBeta: "Private beta", contact: "Contact", legal: "Legal", privacy: "Privacy Policy", terms: "Terms of Service", dataDeletion: "Data Deletion", copyright: "© 2026 TRAPEAK. Private beta." },
  auth: { eyebrow: "TRAPEAK ACCOUNT", signInTitle: "Welcome back.", signInDescription: "Sign in to manage your personal fitness and health data.", signInSetup: "Account access is being configured. Please check back soon.", signUpTitle: "Create your account.", signUpDescription: "Keep every connection and record isolated and under your control.", signUpSetup: "Account registration is being configured. Please check back soon." },
  nav: { overview: "Overview", training: "Training", nutrition: "Nutrition", health: "Health", sharedAccess: "Shared access", connections: "Connections", profile: "Profile & preferences", accountData: "Account data" },
  dashboard: { overview: "OVERVIEW", title: "Your data, organized.", intro: "See the context that an AI—or a person you authorize—can use. Detailed records stay in their own category.", dataOverview: "Data overview", noWorkouts: "No workouts", workout: "Workout", durationUnavailable: "duration unavailable", connectWahoo: "Connect Wahoo to start a structured training history.", activities7: "activities in 7 days", openTraining: "Open training →", nutritionToday: "NUTRITION · TODAY", nothingLogged: "Nothing logged", recordFood: "Record food by voice or text through your connected AI.", openNutrition: "Open nutrition →", noLabs: "No lab reports", healthSeparate: "Health stays separate from training and nutrition access.", openHealth: "Open health →", profileContext: "PROFILE CONTEXT", goalsContext: "Goals, constraints and preferences make AI analysis more relevant.", updateWithAi: "Update through your connected AI", noGrants: "No active grants", shareByEmail: "Share selected categories by email, with an expiry.", manageAccess: "Manage access →", noWearable: "No wearable", workoutsStored: "workouts stored.", otherDataWithAi: "Nutrition, weight, profile and labs can still be saved through AI.", manageConnections: "Manage connections →", boundaries: "DATA BOUNDARIES", boundaryTitle: "Three categories. No hidden bundle.", trainingDescription: "Workouts, training load, goals and practical constraints.", nutritionDescription: "Meals, macros, dietary context and dated weight history.", healthDescription: "Laboratory results, conditions, injuries, contraindications and medications." },
  training: { title: "Workouts and load context.", intro: "Completed sessions, recent patterns and source coverage. TRAPEAK supplies context—not a readiness score or an automatic prescription.", unavailable: "Training data is not available.", unavailableHint: "Connect Wahoo or finish configuring storage, then return here.", openConnections: "Open connections", last7: "LAST 7 DAYS", trainingTime: "TRAINING TIME", previous7: "PREVIOUS 7 DAYS", consecutive: "CONSECUTIVE DAYS", activities: "activities", days: "training days", recent: "RECENT HISTORY", completed: "Completed workouts.", in28: "in the last 28 days", noCompleted: "No completed workouts stored for this period.", activity: "Activity", askAi: "ASK AN AI", prompt: "Compare my last two weeks and suggest the purpose of today's session. Ask for a current check-in first.", coverage: "SOURCE COVERAGE", limitations: "Known limitations." },
  nutrition: { title: "Daily totals, meals on demand.", intro: "Start with the day-level picture. Open individual days only when you need meal details and assumptions.", summary: "Nutrition summary", today: "TODAY", kilocalories: "kilocalories", protein: "PROTEIN", carbohydrates: "CARBOHYDRATES", latestWeight: "LATEST WEIGHT", noMeasurement: "no measurement", unavailable: "Nutrition storage is unavailable.", unavailableHint: "Finish configuring database storage, then return here.", history: "HISTORY", byDay: "Nutrition by day.", recentEntries: "recent entries", noRecords: "No nutrition records yet.", example: "Try: “Save breakfast: an omelette, avocado and two crispbreads.”", entries: "entries", openDetails: "Open details", estimated: "estimated", assumptions: "Assumptions", recordNaturally: "RECORD NATURALLY", recordHint: "Use voice, text or an image in your chosen AI. Ask it to state assumptions before saving estimated calories and macros.", confirmDelete: "Permanently delete this nutrition entry?" },
  health: { title: "Sensitive context, kept separate.", intro: "Laboratory history, conditions, injuries, contraindications and medications. Health access is never implied by Training access.", laboratory: "LABORATORY", reports: "Stored reports.", unavailable: "Laboratory storage is unavailable.", noReports: "No laboratory reports stored.", saveHint: "Ask your AI to extract exact values, units and reference ranges before saving.", collected: "collected", results: "results", conditions: "CONDITIONS", noConditions: "No conditions recorded.", injuries: "INJURIES", noInjuries: "No injuries recorded.", contraindications: "CONTRAINDICATIONS", noContraindications: "No contraindications recorded.", medications: "MEDICATIONS", noMedications: "No medications recorded.", detailsMissing: "Details not recorded", adviceTitle: "Not medical advice.", advice: "TRAPEAK stores user-provided facts and reported values. AI can help organize questions but cannot replace a qualified clinician.", confirmDelete: "Permanently delete this laboratory report and all stored results?" },
  connections: { title: "Your sources.", intro: "Connected sources contribute dated facts. Missing measurements stay missing—they are never replaced with estimates.", available: "AVAILABLE NOW", connected: "CONNECTED", reconnect: "RECONNECT", notConnected: "NOT CONNECTED", connectedAs: "Connected as", storedWorkouts: "Stored workouts", lastSync: "Last synchronization", automatic: "Automatic updates", enabled: "Enabled", manual: "Manual synchronization", notAvailable: "Not available", sync: "Sync Wahoo data", disconnect: "Disconnect", expired: "Wahoo access expired. Reconnect to restore synchronization.", import: "Import authorized completed workouts into your personal TRAPEAK history.", connect: "Connect Wahoo", storageMissing: "Integration storage is not configured.", roadmap: "SOURCE ROADMAP", planned: "Planned · pending provider approval", noRecovery: "No supported source yet" },
  access: { eyebrow: "SHARED ACCESS", title: "Your data. Your permission.", intro: "Invite a coach, doctor, dietitian or another person by email. Choose exact categories, set an expiry and revoke at any time.", newInvitation: "NEW INVITATION", chooseShare: "Choose what to share.", readonlyNotice: "Access is read-only. The recipient must sign in with the same email before accepting.", rules: "ACCESS RULES", rule1: "Training, Nutrition and Health are independent categories.", rule2: "No category grants access to another category.", rule3: "Every read is checked against the active grant and written to the audit trail.", outgoing: "OUTGOING", peopleAccess: "People with access.", total: "total", none: "No invitations yet.", incoming: "INCOMING", sharedWithYou: "Data shared with you.", active: "active", noneIncoming: "No active shared access.", sharedUser: "Shared TRAPEAK user", expires: "expires", activity: "Access activity", events: "events", noneEvents: "No access activity yet.", training: "Training", nutrition: "Nutrition", health: "Health", recoveryLegacy: "Recovery (legacy)", email: "Person's email", categories: "Choose data categories", trainingDescription: "Workouts, load, goals and training constraints", nutritionDescription: "Meals, macros, dietary context and dated weight", healthDescription: "Labs, conditions, injuries and medications", recoveryDescription: "Reserved until a supported source is available", healthWarning: "Health includes laboratory results, conditions, injuries, contraindications and medications.", period: "Access period", days7: "7 days", days30: "30 days", days90: "90 days", year1: "1 year", creating: "Creating…", create: "Create invitation", invitationError: "Access invitation could not be created.", invitationLink: "Invitation link", linkHint: "Send this one-time link only to the specified email.", revoking: "Revoking…", revoke: "Revoke", invitationEyebrow: "ACCESS INVITATION", invitationTitle: "Someone shared TRAPEAK data with you.", invitationIntro: "Accepting binds this invitation to your signed-in account. It is read-only, limited by category and expiry, and can be revoked by the owner.", accepting: "Accepting…", accept: "Accept read-only access", rejecting: "Rejecting…", reject: "Reject", responseError: "Invitation response could not be saved." },
  profile: { eyebrow: "PROFILE & PREFERENCES", title: "Your interface, your units.", intro: "Language, time zone and measurement system are separate choices. None of them determines the language you use with AI.", interface: "INTERFACE", interfaceHint: "These preferences affect presentation only; stored health and fitness values remain structured and language-neutral.", language: "Interface language", timeZone: "Time zone", timeZoneHint: "Use an IANA name such as Europe/Warsaw.", measurement: "Measurement system", measurementHint: "Metric uses kilograms and kilometres; imperial uses pounds and miles.", metric: "Metric", imperial: "Imperial", save: "Save preferences", saving: "Saving…", saved: "Preferences saved.", error: "Preferences could not be saved.", independence: "INDEPENDENT SETTINGS", independenceText: "Changing interface language does not change your time zone, units, stored data or the language used by ChatGPT, Claude or another AI." },
  status: { connected: "Wahoo connected successfully.", disconnected: "Wahoo disconnected.", denied: "Wahoo authorization was cancelled.", invalidState: "The connection request expired. Please try again.", alreadyLinked: "This Wahoo account is already linked to another TRAPEAK account.", error: "Wahoo could not be connected. Please try again.", disconnectError: "Wahoo could not be disconnected. Please try again.", notConnected: "Connect Wahoo before synchronizing workout data.", reconnectRequired: "Wahoo access expired. Reconnect to continue syncing.", syncError: "Wahoo data could not be synchronized. Please try again.", syncSuccess: "Wahoo synchronized: {received} received, {created} new, {updated} updated." },
};

const ptBR: UiMessages = {
  common: { home: "Início", dashboard: "Painel", how: "Como funciona", examples: "Exemplos", useCases: "Casos de uso", faq: "Dúvidas", menu: "Menu", signIn: "Entrar", createAccount: "Criar conta", earlyAccess: "Pedir acesso", language: "Idioma", backHome: "Voltar ao TRAPEAK", delete: "Excluir", unavailable: "Indisponível", notRecorded: "Não informado", readGuide: "Ler o guia →", privateBeta: "Beta privado", contact: "Contato", legal: "Legal", privacy: "Política de Privacidade", terms: "Termos de Uso", dataDeletion: "Exclusão de dados", copyright: "© 2026 TRAPEAK. Beta privado." },
  auth: { eyebrow: "CONTA TRAPEAK", signInTitle: "Que bom ter você de volta.", signInDescription: "Entre para gerenciar seus dados pessoais de treino e saúde.", signInSetup: "O acesso à conta está sendo configurado. Tente novamente em breve.", signUpTitle: "Crie sua conta.", signUpDescription: "Mantenha cada conexão e registro isolado e sob seu controle.", signUpSetup: "O cadastro está sendo configurado. Tente novamente em breve." },
  nav: { overview: "Visão geral", training: "Treinos", nutrition: "Alimentação", health: "Saúde", sharedAccess: "Acesso compartilhado", connections: "Conexões", profile: "Perfil e preferências", accountData: "Dados da conta" },
  dashboard: { overview: "VISÃO GERAL", title: "Seus dados, organizados.", intro: "Veja o contexto que uma IA — ou alguém autorizado — pode usar. Os registros detalhados ficam em suas categorias.", dataOverview: "Visão geral dos dados", noWorkouts: "Sem treinos", workout: "Treino", durationUnavailable: "duração indisponível", connectWahoo: "Conecte o Wahoo para iniciar seu histórico estruturado.", activities7: "atividades em 7 dias", openTraining: "Abrir treinos →", nutritionToday: "ALIMENTAÇÃO · HOJE", nothingLogged: "Nada registrado", recordFood: "Registre refeições por voz ou texto na IA conectada.", openNutrition: "Abrir alimentação →", noLabs: "Sem exames", healthSeparate: "Saúde permanece separada dos acessos a treino e alimentação.", openHealth: "Abrir saúde →", profileContext: "CONTEXTO DO PERFIL", goalsContext: "Metas, limites e preferências tornam a análise da IA mais relevante.", updateWithAi: "Atualizar pela IA conectada", noGrants: "Sem acessos ativos", shareByEmail: "Compartilhe categorias por e-mail e defina uma validade.", manageAccess: "Gerenciar acesso →", noWearable: "Sem dispositivo", workoutsStored: "treinos armazenados.", otherDataWithAi: "Alimentação, peso, perfil e exames ainda podem ser salvos pela IA.", manageConnections: "Gerenciar conexões →", boundaries: "LIMITES DOS DADOS", boundaryTitle: "Três categorias. Nenhum pacote oculto.", trainingDescription: "Treinos, carga, metas e restrições práticas.", nutritionDescription: "Refeições, macros, contexto alimentar e histórico de peso.", healthDescription: "Exames, condições, lesões, contraindicações e medicamentos." },
  training: { title: "Treinos e contexto de carga.", intro: "Sessões concluídas, padrões recentes e cobertura das fontes. O TRAPEAK fornece contexto, não uma pontuação automática de prontidão.", unavailable: "Os dados de treino não estão disponíveis.", unavailableHint: "Conecte o Wahoo ou conclua a configuração do armazenamento.", openConnections: "Abrir conexões", last7: "ÚLTIMOS 7 DIAS", trainingTime: "TEMPO DE TREINO", previous7: "7 DIAS ANTERIORES", consecutive: "DIAS CONSECUTIVOS", activities: "atividades", days: "dias de treino", recent: "HISTÓRICO RECENTE", completed: "Treinos concluídos.", in28: "nos últimos 28 dias", noCompleted: "Nenhum treino concluído neste período.", activity: "Atividade", askAi: "PERGUNTE À IA", prompt: "Compare minhas últimas duas semanas e sugira o objetivo do treino de hoje. Antes, pergunte como estou.", coverage: "COBERTURA DAS FONTES", limitations: "Limitações conhecidas." },
  nutrition: { title: "Totais diários, refeições quando precisar.", intro: "Comece pelo resumo do dia. Abra uma data apenas para ver detalhes e premissas.", summary: "Resumo alimentar", today: "HOJE", kilocalories: "quilocalorias", protein: "PROTEÍNA", carbohydrates: "CARBOIDRATOS", latestWeight: "PESO MAIS RECENTE", noMeasurement: "sem medição", unavailable: "O armazenamento de alimentação está indisponível.", unavailableHint: "Conclua a configuração do banco de dados.", history: "HISTÓRICO", byDay: "Alimentação por dia.", recentEntries: "registros recentes", noRecords: "Nenhum registro de alimentação.", example: "Experimente: “Salve o café da manhã: omelete, abacate e duas torradas.”", entries: "registros", openDetails: "Abrir detalhes", estimated: "estimado", assumptions: "Premissas", recordNaturally: "REGISTRE NATURALMENTE", recordHint: "Use voz, texto ou imagem na IA escolhida. Peça que informe as premissas antes de salvar estimativas.", confirmDelete: "Excluir este registro de alimentação permanentemente?" },
  health: { title: "Contexto sensível, mantido separado.", intro: "Histórico de exames, condições, lesões, contraindicações e medicamentos. Acesso a Treinos nunca inclui Saúde.", laboratory: "EXAMES", reports: "Relatórios armazenados.", unavailable: "O armazenamento de exames está indisponível.", noReports: "Nenhum exame armazenado.", saveHint: "Peça à IA que extraia valores, unidades e referências exatos antes de salvar.", collected: "coletado em", results: "resultados", conditions: "CONDIÇÕES", noConditions: "Nenhuma condição registrada.", injuries: "LESÕES", noInjuries: "Nenhuma lesão registrada.", contraindications: "CONTRAINDICAÇÕES", noContraindications: "Nenhuma contraindicação registrada.", medications: "MEDICAMENTOS", noMedications: "Nenhum medicamento registrado.", detailsMissing: "Detalhes não informados", adviceTitle: "Não é orientação médica.", advice: "O TRAPEAK armazena fatos e resultados informados. A IA pode organizar perguntas, mas não substitui um profissional qualificado.", confirmDelete: "Excluir este exame e todos os resultados permanentemente?" },
  connections: { title: "Suas fontes.", intro: "Fontes conectadas adicionam fatos datados. Medições ausentes continuam ausentes — nunca são estimadas.", available: "DISPONÍVEL AGORA", connected: "CONECTADO", reconnect: "RECONECTAR", notConnected: "NÃO CONECTADO", connectedAs: "Conectado como", storedWorkouts: "Treinos armazenados", lastSync: "Última sincronização", automatic: "Atualizações automáticas", enabled: "Ativadas", manual: "Sincronização manual", notAvailable: "Indisponível", sync: "Sincronizar dados do Wahoo", disconnect: "Desconectar", expired: "O acesso ao Wahoo expirou. Reconecte para restaurar a sincronização.", import: "Importe treinos concluídos e autorizados para seu histórico TRAPEAK.", connect: "Conectar Wahoo", storageMissing: "O armazenamento da integração não está configurado.", roadmap: "PRÓXIMAS FONTES", planned: "Planejado · aguardando aprovação", noRecovery: "Ainda sem fonte compatível" },
  access: { eyebrow: "ACESSO COMPARTILHADO", title: "Seus dados. Sua permissão.", intro: "Convide treinador, médico, nutricionista ou outra pessoa por e-mail. Escolha categorias, validade e revogue quando quiser.", newInvitation: "NOVO CONVITE", chooseShare: "Escolha o que compartilhar.", readonlyNotice: "O acesso é somente leitura. A pessoa deve entrar com o mesmo e-mail antes de aceitar.", rules: "REGRAS DE ACESSO", rule1: "Treinos, Alimentação e Saúde são categorias independentes.", rule2: "Nenhuma categoria libera outra categoria.", rule3: "Cada leitura valida a permissão ativa e entra no histórico de auditoria.", outgoing: "ENVIADOS", peopleAccess: "Pessoas com acesso.", total: "total", none: "Nenhum convite ainda.", incoming: "RECEBIDOS", sharedWithYou: "Dados compartilhados com você.", active: "ativos", noneIncoming: "Nenhum acesso compartilhado ativo.", sharedUser: "Usuário TRAPEAK", expires: "vence em", activity: "Atividade de acesso", events: "eventos", noneEvents: "Nenhuma atividade ainda.", training: "Treinos", nutrition: "Alimentação", health: "Saúde", recoveryLegacy: "Recuperação (legado)", email: "E-mail da pessoa", categories: "Escolha as categorias", trainingDescription: "Treinos, carga, metas e restrições", nutritionDescription: "Refeições, macros, contexto alimentar e peso", healthDescription: "Exames, condições, lesões e medicamentos", recoveryDescription: "Reservado até existir uma fonte compatível", healthWarning: "Saúde inclui exames, condições, lesões, contraindicações e medicamentos.", period: "Prazo de acesso", days7: "7 dias", days30: "30 dias", days90: "90 dias", year1: "1 ano", creating: "Criando…", create: "Criar convite", invitationError: "Não foi possível criar o convite.", invitationLink: "Link do convite", linkHint: "Envie este link de uso único somente ao e-mail informado.", revoking: "Revogando…", revoke: "Revogar", invitationEyebrow: "CONVITE DE ACESSO", invitationTitle: "Alguém compartilhou dados do TRAPEAK com você.", invitationIntro: "Ao aceitar, o convite fica vinculado à sua conta. O acesso é somente leitura, limitado por categoria e validade.", accepting: "Aceitando…", accept: "Aceitar acesso de leitura", rejecting: "Recusando…", reject: "Recusar", responseError: "Não foi possível salvar a resposta." },
  profile: { eyebrow: "PERFIL E PREFERÊNCIAS", title: "Sua interface, suas unidades.", intro: "Idioma, fuso horário e sistema de medidas são escolhas separadas. Nenhuma define o idioma usado com a IA.", interface: "INTERFACE", interfaceHint: "As preferências afetam apenas a apresentação; os dados continuam estruturados e neutros em relação ao idioma.", language: "Idioma da interface", timeZone: "Fuso horário", timeZoneHint: "Use um nome IANA, como America/Sao_Paulo.", measurement: "Sistema de medidas", measurementHint: "Métrico usa quilos e quilômetros; imperial usa libras e milhas.", metric: "Métrico", imperial: "Imperial", save: "Salvar preferências", saving: "Salvando…", saved: "Preferências salvas.", error: "Não foi possível salvar as preferências.", independence: "CONFIGURAÇÕES INDEPENDENTES", independenceText: "Mudar o idioma não altera fuso, unidades, dados armazenados nem o idioma usado pelo ChatGPT, Claude ou outra IA." },
  status: { connected: "Wahoo conectado com sucesso.", disconnected: "Wahoo desconectado.", denied: "A autorização do Wahoo foi cancelada.", invalidState: "A solicitação expirou. Tente novamente.", alreadyLinked: "Esta conta Wahoo já está vinculada a outra conta TRAPEAK.", error: "Não foi possível conectar o Wahoo.", disconnectError: "Não foi possível desconectar o Wahoo.", notConnected: "Conecte o Wahoo antes de sincronizar.", reconnectRequired: "O acesso ao Wahoo expirou. Reconecte para continuar.", syncError: "Não foi possível sincronizar os dados do Wahoo.", syncSuccess: "Wahoo sincronizado: {received} recebidos, {created} novos, {updated} atualizados." },
};

// The remaining locale dictionaries are complete rather than partial overlays. This keeps
// missing translations a type error and makes adding the eighth locale a data-only change.
const es419: UiMessages = JSON.parse(JSON.stringify(ptBR)) as UiMessages;
const id: UiMessages = JSON.parse(JSON.stringify(en)) as UiMessages;
const vi: UiMessages = JSON.parse(JSON.stringify(en)) as UiMessages;
const hi: UiMessages = JSON.parse(JSON.stringify(en)) as UiMessages;
const bn: UiMessages = JSON.parse(JSON.stringify(en)) as UiMessages;

Object.assign(es419, {
  common: { home: "Inicio", dashboard: "Panel", how: "Cómo funciona", examples: "Ejemplos", useCases: "Casos de uso", faq: "Preguntas", menu: "Menú", signIn: "Iniciar sesión", createAccount: "Crear cuenta", earlyAccess: "Solicitar acceso", language: "Idioma", backHome: "Volver a TRAPEAK", delete: "Eliminar", unavailable: "No disponible", notRecorded: "Sin registrar", readGuide: "Leer la guía →", privateBeta: "Beta privada", contact: "Contacto", legal: "Legal", privacy: "Política de Privacidad", terms: "Términos del Servicio", dataDeletion: "Eliminación de datos", copyright: "© 2026 TRAPEAK. Beta privada." },
  nav: { overview: "Resumen", training: "Entrenamiento", nutrition: "Nutrición", health: "Salud", sharedAccess: "Acceso compartido", connections: "Conexiones", profile: "Perfil y preferencias", accountData: "Datos de la cuenta" },
  auth: { eyebrow: "CUENTA TRAPEAK", signInTitle: "Qué bueno verte de nuevo.", signInDescription: "Inicia sesión para administrar tus datos personales de entrenamiento y salud.", signInSetup: "El acceso a la cuenta se está configurando. Vuelve pronto.", signUpTitle: "Crea tu cuenta.", signUpDescription: "Mantén cada conexión y registro aislado y bajo tu control.", signUpSetup: "El registro se está configurando. Vuelve pronto." },
  profile: { eyebrow: "PERFIL Y PREFERENCIAS", title: "Tu interfaz, tus unidades.", intro: "El idioma, la zona horaria y el sistema de medidas son opciones independientes. Ninguna define el idioma que usas con la IA.", interface: "INTERFAZ", interfaceHint: "Estas preferencias solo cambian la presentación; los datos siguen siendo estructurados y neutrales.", language: "Idioma de la interfaz", timeZone: "Zona horaria", timeZoneHint: "Usa un nombre IANA, como America/Mexico_City.", measurement: "Sistema de medidas", measurementHint: "Métrico usa kilogramos y kilómetros; imperial usa libras y millas.", metric: "Métrico", imperial: "Imperial", save: "Guardar preferencias", saving: "Guardando…", saved: "Preferencias guardadas.", error: "No se pudieron guardar las preferencias.", independence: "AJUSTES INDEPENDIENTES", independenceText: "Cambiar el idioma no modifica la zona horaria, las unidades, los datos guardados ni el idioma usado por ChatGPT, Claude u otra IA." },
  dashboard: { overview: "RESUMEN", title: "Tus datos, organizados.", intro: "Consulta el contexto que puede usar una IA —o una persona autorizada—. Los registros detallados permanecen en su categoría.", dataOverview: "Resumen de datos", noWorkouts: "Sin entrenamientos", workout: "Entrenamiento", durationUnavailable: "duración no disponible", connectWahoo: "Conecta Wahoo para iniciar un historial estructurado de entrenamiento.", activities7: "actividades en 7 días", openTraining: "Abrir entrenamiento →", nutritionToday: "NUTRICIÓN · HOY", nothingLogged: "Nada registrado", recordFood: "Registra alimentos por voz o texto mediante tu IA conectada.", openNutrition: "Abrir nutrición →", noLabs: "Sin informes de laboratorio", healthSeparate: "Salud se mantiene separada del acceso a Entrenamiento y Nutrición.", openHealth: "Abrir salud →", profileContext: "CONTEXTO DEL PERFIL", goalsContext: "Los objetivos, límites y preferencias hacen más relevante el análisis de la IA.", updateWithAi: "Actualizar mediante tu IA conectada", noGrants: "Sin permisos activos", shareByEmail: "Comparte categorías seleccionadas por correo y define una fecha de vencimiento.", manageAccess: "Administrar acceso →", noWearable: "Sin dispositivo", workoutsStored: "entrenamientos guardados.", otherDataWithAi: "La nutrición, el peso, el perfil y los análisis también pueden guardarse mediante IA.", manageConnections: "Administrar conexiones →", boundaries: "LÍMITES DE DATOS", boundaryTitle: "Tres categorías. Ningún paquete oculto.", trainingDescription: "Entrenamientos, carga, objetivos y límites prácticos.", nutritionDescription: "Comidas, macros, contexto alimentario e historial de peso.", healthDescription: "Laboratorio, condiciones, lesiones, contraindicaciones y medicamentos." },
  training: { title: "Entrenamientos y contexto de carga.", intro: "Sesiones completadas, patrones recientes y cobertura de fuentes. TRAPEAK aporta contexto, no una puntuación de preparación ni una prescripción automática.", unavailable: "Los datos de entrenamiento no están disponibles.", unavailableHint: "Conecta Wahoo o termina de configurar el almacenamiento y vuelve aquí.", openConnections: "Abrir conexiones", last7: "ÚLTIMOS 7 DÍAS", trainingTime: "TIEMPO DE ENTRENAMIENTO", previous7: "7 DÍAS ANTERIORES", consecutive: "DÍAS CONSECUTIVOS", activities: "actividades", days: "días de entrenamiento", recent: "HISTORIAL RECIENTE", completed: "Entrenamientos completados.", in28: "en los últimos 28 días", noCompleted: "No hay entrenamientos completados en este período.", activity: "Actividad", askAi: "PREGUNTA A UNA IA", prompt: "Compara mis últimas dos semanas y sugiere el propósito del entrenamiento de hoy. Primero pregúntame cómo me siento.", coverage: "COBERTURA DE FUENTES", limitations: "Limitaciones conocidas." },
  nutrition: { title: "Totales diarios, comidas cuando las necesites.", intro: "Empieza por el resumen del día. Abre una fecha solo cuando necesites detalles y supuestos.", summary: "Resumen nutricional", today: "HOY", kilocalories: "kilocalorías", protein: "PROTEÍNA", carbohydrates: "CARBOHIDRATOS", latestWeight: "PESO MÁS RECIENTE", noMeasurement: "sin medición", unavailable: "El almacenamiento de nutrición no está disponible.", unavailableHint: "Termina de configurar la base de datos y vuelve aquí.", history: "HISTORIAL", byDay: "Nutrición por día.", recentEntries: "registros recientes", noRecords: "Aún no hay registros de nutrición.", example: "Prueba: «Guarda el desayuno: omelet, aguacate y dos tostadas». ", entries: "registros", openDetails: "Abrir detalles", estimated: "estimado", assumptions: "Supuestos", recordNaturally: "REGISTRA DE FORMA NATURAL", recordHint: "Usa voz, texto o una imagen en la IA que elijas. Pídele que indique los supuestos antes de guardar calorías y macros estimados.", confirmDelete: "¿Eliminar permanentemente este registro de nutrición?" },
  health: { title: "Contexto sensible, siempre separado.", intro: "Historial de laboratorio, condiciones, lesiones, contraindicaciones y medicamentos. El acceso a Entrenamiento nunca implica acceso a Salud.", laboratory: "LABORATORIO", reports: "Informes guardados.", unavailable: "El almacenamiento de laboratorio no está disponible.", noReports: "No hay informes de laboratorio guardados.", saveHint: "Pide a la IA que extraiga valores, unidades y rangos exactos antes de guardar.", collected: "recogido el", results: "resultados", conditions: "CONDICIONES", noConditions: "No hay condiciones registradas.", injuries: "LESIONES", noInjuries: "No hay lesiones registradas.", contraindications: "CONTRAINDICACIONES", noContraindications: "No hay contraindicaciones registradas.", medications: "MEDICAMENTOS", noMedications: "No hay medicamentos registrados.", detailsMissing: "Detalles no registrados", adviceTitle: "No es consejo médico.", advice: "TRAPEAK guarda hechos y valores proporcionados por el usuario. La IA puede ayudar a organizar preguntas, pero no sustituye a un profesional cualificado.", confirmDelete: "¿Eliminar permanentemente este informe y todos sus resultados?" },
  connections: { title: "Tus fuentes.", intro: "Las fuentes conectadas aportan hechos con fecha. Las mediciones ausentes siguen ausentes: nunca se sustituyen por estimaciones.", available: "DISPONIBLE AHORA", connected: "CONECTADO", reconnect: "RECONECTAR", notConnected: "NO CONECTADO", connectedAs: "Conectado como", storedWorkouts: "Entrenamientos guardados", lastSync: "Última sincronización", automatic: "Actualizaciones automáticas", enabled: "Activadas", manual: "Sincronización manual", notAvailable: "No disponible", sync: "Sincronizar datos de Wahoo", disconnect: "Desconectar", expired: "El acceso a Wahoo venció. Vuelve a conectarlo para restaurar la sincronización.", import: "Importa entrenamientos completados y autorizados a tu historial personal de TRAPEAK.", connect: "Conectar Wahoo", storageMissing: "El almacenamiento de la integración no está configurado.", roadmap: "PRÓXIMAS FUENTES", planned: "Planificado · pendiente de aprobación", noRecovery: "Todavía no hay una fuente compatible" },
  access: { eyebrow: "ACCESO COMPARTIDO", title: "Tus datos. Tu permiso.", intro: "Invita por correo a un entrenador, médico, nutricionista u otra persona. Elige categorías, vencimiento y revoca cuando quieras.", newInvitation: "NUEVA INVITACIÓN", chooseShare: "Elige qué compartir.", readonlyNotice: "El acceso es de solo lectura. La persona debe iniciar sesión con el mismo correo antes de aceptar.", rules: "REGLAS DE ACCESO", rule1: "Entrenamiento, Nutrición y Salud son categorías independientes.", rule2: "Ninguna categoría da acceso a otra.", rule3: "Cada lectura comprueba el permiso activo y se guarda en el registro de auditoría.", outgoing: "ENVIADOS", peopleAccess: "Personas con acceso.", total: "total", none: "Aún no hay invitaciones.", incoming: "RECIBIDOS", sharedWithYou: "Datos compartidos contigo.", active: "activos", noneIncoming: "No hay accesos compartidos activos.", sharedUser: "Usuario de TRAPEAK", expires: "vence", activity: "Actividad de acceso", events: "eventos", noneEvents: "Aún no hay actividad.", training: "Entrenamiento", nutrition: "Nutrición", health: "Salud", recoveryLegacy: "Recuperación (legado)", email: "Correo de la persona", categories: "Elige categorías de datos", trainingDescription: "Entrenamientos, carga, objetivos y límites", nutritionDescription: "Comidas, macros, contexto alimentario y peso", healthDescription: "Laboratorio, condiciones, lesiones y medicamentos", recoveryDescription: "Reservado hasta disponer de una fuente compatible", healthWarning: "Salud incluye laboratorio, condiciones, lesiones, contraindicaciones y medicamentos.", period: "Duración del acceso", days7: "7 días", days30: "30 días", days90: "90 días", year1: "1 año", creating: "Creando…", create: "Crear invitación", invitationError: "No se pudo crear la invitación.", invitationLink: "Enlace de invitación", linkHint: "Envía este enlace de un solo uso únicamente al correo indicado.", revoking: "Revocando…", revoke: "Revocar", invitationEyebrow: "INVITACIÓN DE ACCESO", invitationTitle: "Alguien compartió datos de TRAPEAK contigo.", invitationIntro: "Al aceptar, la invitación queda vinculada a tu cuenta. Es de solo lectura, está limitada por categoría y vencimiento, y el titular puede revocarla.", accepting: "Aceptando…", accept: "Aceptar acceso de lectura", rejecting: "Rechazando…", reject: "Rechazar", responseError: "No se pudo guardar la respuesta." },
  status: { connected: "Wahoo se conectó correctamente.", disconnected: "Wahoo se desconectó.", denied: "Se canceló la autorización de Wahoo.", invalidState: "La solicitud de conexión venció. Inténtalo de nuevo.", alreadyLinked: "Esta cuenta de Wahoo ya está vinculada a otra cuenta de TRAPEAK.", error: "No se pudo conectar Wahoo. Inténtalo de nuevo.", disconnectError: "No se pudo desconectar Wahoo. Inténtalo de nuevo.", notConnected: "Conecta Wahoo antes de sincronizar entrenamientos.", reconnectRequired: "El acceso a Wahoo venció. Reconecta para continuar.", syncError: "No se pudieron sincronizar los datos de Wahoo.", syncSuccess: "Wahoo sincronizado: {received} recibidos, {created} nuevos, {updated} actualizados." },
});

Object.assign(id, {
  common: { home: "Beranda", dashboard: "Dasbor", how: "Cara kerja", examples: "Contoh", useCases: "Kegunaan", faq: "Tanya jawab", menu: "Menu", signIn: "Masuk", createAccount: "Buat akun", earlyAccess: "Minta akses", language: "Bahasa", backHome: "Kembali ke TRAPEAK", delete: "Hapus", unavailable: "Tidak tersedia", notRecorded: "Belum dicatat", readGuide: "Baca panduan →", privateBeta: "Beta privat", contact: "Kontak", legal: "Legal", privacy: "Kebijakan Privasi", terms: "Ketentuan Layanan", dataDeletion: "Penghapusan data", copyright: "© 2026 TRAPEAK. Beta privat." },
  nav: { overview: "Ringkasan", training: "Latihan", nutrition: "Nutrisi", health: "Kesehatan", sharedAccess: "Akses berbagi", connections: "Koneksi", profile: "Profil & preferensi", accountData: "Data akun" },
  auth: { eyebrow: "AKUN TRAPEAK", signInTitle: "Selamat datang kembali.", signInDescription: "Masuk untuk mengelola data latihan dan kesehatan pribadi Anda.", signInSetup: "Akses akun sedang disiapkan. Silakan kembali lagi.", signUpTitle: "Buat akun Anda.", signUpDescription: "Simpan setiap koneksi dan catatan secara terpisah dan dalam kendali Anda.", signUpSetup: "Pendaftaran akun sedang disiapkan. Silakan kembali lagi." },
  profile: { eyebrow: "PROFIL & PREFERENSI", title: "Antarmuka dan satuan pilihan Anda.", intro: "Bahasa, zona waktu, dan sistem pengukuran adalah pilihan terpisah. Tidak ada yang menentukan bahasa percakapan dengan AI.", interface: "ANTARMUKA", interfaceHint: "Preferensi ini hanya memengaruhi tampilan; data tetap terstruktur dan netral bahasa.", language: "Bahasa antarmuka", timeZone: "Zona waktu", timeZoneHint: "Gunakan nama IANA seperti Asia/Jakarta.", measurement: "Sistem pengukuran", measurementHint: "Metrik memakai kilogram dan kilometer; imperial memakai pon dan mil.", metric: "Metrik", imperial: "Imperial", save: "Simpan preferensi", saving: "Menyimpan…", saved: "Preferensi tersimpan.", error: "Preferensi tidak dapat disimpan.", independence: "PENGATURAN TERPISAH", independenceText: "Mengganti bahasa tidak mengubah zona waktu, satuan, data tersimpan, atau bahasa ChatGPT, Claude, maupun AI lain." },
  dashboard: { overview: "RINGKASAN", title: "Data Anda, tertata.", intro: "Lihat konteks yang dapat digunakan AI—atau orang yang Anda izinkan. Catatan terperinci tetap berada di kategorinya.", dataOverview: "Ringkasan data", noWorkouts: "Belum ada latihan", workout: "Latihan", durationUnavailable: "durasi tidak tersedia", connectWahoo: "Hubungkan Wahoo untuk memulai riwayat latihan terstruktur.", activities7: "aktivitas dalam 7 hari", openTraining: "Buka latihan →", nutritionToday: "NUTRISI · HARI INI", nothingLogged: "Belum ada catatan", recordFood: "Catat makanan lewat suara atau teks melalui AI terhubung.", openNutrition: "Buka nutrisi →", noLabs: "Belum ada laporan lab", healthSeparate: "Kesehatan tetap terpisah dari akses Latihan dan Nutrisi.", openHealth: "Buka kesehatan →", profileContext: "KONTEKS PROFIL", goalsContext: "Tujuan, batasan, dan preferensi membuat analisis AI lebih relevan.", updateWithAi: "Perbarui melalui AI terhubung", noGrants: "Belum ada izin aktif", shareByEmail: "Bagikan kategori tertentu lewat email dengan masa berlaku.", manageAccess: "Kelola akses →", noWearable: "Belum ada perangkat", workoutsStored: "latihan tersimpan.", otherDataWithAi: "Nutrisi, berat, profil, dan lab tetap dapat disimpan melalui AI.", manageConnections: "Kelola koneksi →", boundaries: "BATAS DATA", boundaryTitle: "Tiga kategori. Tanpa paket tersembunyi.", trainingDescription: "Latihan, beban, tujuan, dan batasan praktis.", nutritionDescription: "Makanan, makro, konteks diet, dan riwayat berat.", healthDescription: "Hasil lab, kondisi, cedera, kontraindikasi, dan obat." },
  training: { title: "Latihan dan konteks beban.", intro: "Sesi selesai, pola terbaru, dan cakupan sumber. TRAPEAK memberi konteks—bukan skor kesiapan atau resep otomatis.", unavailable: "Data latihan tidak tersedia.", unavailableHint: "Hubungkan Wahoo atau selesaikan penyimpanan, lalu kembali ke sini.", openConnections: "Buka koneksi", last7: "7 HARI TERAKHIR", trainingTime: "WAKTU LATIHAN", previous7: "7 HARI SEBELUMNYA", consecutive: "HARI BERTURUT-TURUT", activities: "aktivitas", days: "hari latihan", recent: "RIWAYAT TERBARU", completed: "Latihan selesai.", in28: "dalam 28 hari terakhir", noCompleted: "Belum ada latihan selesai pada periode ini.", activity: "Aktivitas", askAi: "TANYAKAN KE AI", prompt: "Bandingkan dua minggu terakhir dan sarankan tujuan sesi hari ini. Tanyakan dulu kondisi saya sekarang.", coverage: "CAKUPAN SUMBER", limitations: "Batasan yang diketahui." },
  nutrition: { title: "Total harian, detail makanan saat dibutuhkan.", intro: "Mulai dari ringkasan harian. Buka tanggal tertentu hanya jika perlu melihat detail dan asumsi.", summary: "Ringkasan nutrisi", today: "HARI INI", kilocalories: "kilokalori", protein: "PROTEIN", carbohydrates: "KARBOHIDRAT", latestWeight: "BERAT TERBARU", noMeasurement: "belum diukur", unavailable: "Penyimpanan nutrisi tidak tersedia.", unavailableHint: "Selesaikan konfigurasi basis data, lalu kembali ke sini.", history: "RIWAYAT", byDay: "Nutrisi per hari.", recentEntries: "catatan terbaru", noRecords: "Belum ada catatan nutrisi.", example: "Coba: “Simpan sarapan: omelet, alpukat, dan dua roti renyah.”", entries: "catatan", openDetails: "Buka detail", estimated: "perkiraan", assumptions: "Asumsi", recordNaturally: "CATAT SECARA ALAMI", recordHint: "Gunakan suara, teks, atau gambar di AI pilihan Anda. Minta AI menyebutkan asumsi sebelum menyimpan perkiraan kalori dan makro.", confirmDelete: "Hapus catatan nutrisi ini secara permanen?" },
  health: { title: "Konteks sensitif, tetap terpisah.", intro: "Riwayat lab, kondisi, cedera, kontraindikasi, dan obat. Akses Latihan tidak pernah otomatis mencakup Kesehatan.", laboratory: "LABORATORIUM", reports: "Laporan tersimpan.", unavailable: "Penyimpanan laboratorium tidak tersedia.", noReports: "Belum ada laporan laboratorium.", saveHint: "Minta AI mengekstrak nilai, unit, dan rentang referensi persis sebelum menyimpan.", collected: "diambil", results: "hasil", conditions: "KONDISI", noConditions: "Belum ada kondisi yang dicatat.", injuries: "CEDERA", noInjuries: "Belum ada cedera yang dicatat.", contraindications: "KONTRAINDIKASI", noContraindications: "Belum ada kontraindikasi yang dicatat.", medications: "OBAT", noMedications: "Belum ada obat yang dicatat.", detailsMissing: "Detail belum dicatat", adviceTitle: "Bukan nasihat medis.", advice: "TRAPEAK menyimpan fakta dan nilai yang diberikan pengguna. AI dapat membantu menyusun pertanyaan, tetapi tidak menggantikan tenaga medis yang kompeten.", confirmDelete: "Hapus laporan laboratorium ini beserta semua hasilnya secara permanen?" },
  connections: { title: "Sumber data Anda.", intro: "Sumber terhubung menyumbangkan fakta bertanggal. Pengukuran yang tidak ada tetap tidak ada—tidak pernah diganti perkiraan.", available: "TERSEDIA SEKARANG", connected: "TERHUBUNG", reconnect: "HUBUNGKAN ULANG", notConnected: "BELUM TERHUBUNG", connectedAs: "Terhubung sebagai", storedWorkouts: "Latihan tersimpan", lastSync: "Sinkronisasi terakhir", automatic: "Pembaruan otomatis", enabled: "Aktif", manual: "Sinkronisasi manual", notAvailable: "Tidak tersedia", sync: "Sinkronkan data Wahoo", disconnect: "Putuskan", expired: "Akses Wahoo berakhir. Hubungkan ulang untuk memulihkan sinkronisasi.", import: "Impor latihan selesai yang diizinkan ke riwayat TRAPEAK pribadi Anda.", connect: "Hubungkan Wahoo", storageMissing: "Penyimpanan integrasi belum dikonfigurasi.", roadmap: "RENCANA SUMBER", planned: "Direncanakan · menunggu persetujuan", noRecovery: "Belum ada sumber yang didukung" },
  access: { eyebrow: "AKSES BERBAGI", title: "Data Anda. Izin Anda.", intro: "Undang pelatih, dokter, ahli gizi, atau orang lain lewat email. Pilih kategori, masa berlaku, dan cabut kapan saja.", newInvitation: "UNDANGAN BARU", chooseShare: "Pilih yang ingin dibagikan.", readonlyNotice: "Akses hanya-baca. Penerima harus masuk dengan email yang sama sebelum menerima.", rules: "ATURAN AKSES", rule1: "Latihan, Nutrisi, dan Kesehatan adalah kategori terpisah.", rule2: "Satu kategori tidak membuka kategori lain.", rule3: "Setiap pembacaan diperiksa terhadap izin aktif dan dicatat dalam audit.", outgoing: "TERKIRIM", peopleAccess: "Orang yang memiliki akses.", total: "total", none: "Belum ada undangan.", incoming: "DITERIMA", sharedWithYou: "Data yang dibagikan kepada Anda.", active: "aktif", noneIncoming: "Belum ada akses berbagi aktif.", sharedUser: "Pengguna TRAPEAK", expires: "berakhir", activity: "Aktivitas akses", events: "peristiwa", noneEvents: "Belum ada aktivitas akses.", training: "Latihan", nutrition: "Nutrisi", health: "Kesehatan", recoveryLegacy: "Pemulihan (lama)", email: "Email penerima", categories: "Pilih kategori data", trainingDescription: "Latihan, beban, tujuan, dan batasan latihan", nutritionDescription: "Makanan, makro, konteks diet, dan berat bertanggal", healthDescription: "Lab, kondisi, cedera, dan obat", recoveryDescription: "Disiapkan sampai sumber yang didukung tersedia", healthWarning: "Kesehatan mencakup hasil lab, kondisi, cedera, kontraindikasi, dan obat.", period: "Masa akses", days7: "7 hari", days30: "30 hari", days90: "90 hari", year1: "1 tahun", creating: "Membuat…", create: "Buat undangan", invitationError: "Undangan akses tidak dapat dibuat.", invitationLink: "Tautan undangan", linkHint: "Kirim tautan sekali pakai ini hanya ke email yang ditentukan.", revoking: "Mencabut…", revoke: "Cabut", invitationEyebrow: "UNDANGAN AKSES", invitationTitle: "Seseorang membagikan data TRAPEAK kepada Anda.", invitationIntro: "Dengan menerima, undangan ditautkan ke akun Anda. Akses hanya-baca, dibatasi kategori dan masa berlaku, serta dapat dicabut pemilik.", accepting: "Menerima…", accept: "Terima akses hanya-baca", rejecting: "Menolak…", reject: "Tolak", responseError: "Jawaban undangan tidak dapat disimpan." },
  status: { connected: "Wahoo berhasil terhubung.", disconnected: "Wahoo terputus.", denied: "Otorisasi Wahoo dibatalkan.", invalidState: "Permintaan koneksi berakhir. Silakan coba lagi.", alreadyLinked: "Akun Wahoo ini sudah terhubung ke akun TRAPEAK lain.", error: "Wahoo tidak dapat dihubungkan. Silakan coba lagi.", disconnectError: "Wahoo tidak dapat diputuskan. Silakan coba lagi.", notConnected: "Hubungkan Wahoo sebelum menyinkronkan latihan.", reconnectRequired: "Akses Wahoo berakhir. Hubungkan ulang untuk melanjutkan.", syncError: "Data Wahoo tidak dapat disinkronkan.", syncSuccess: "Wahoo tersinkron: {received} diterima, {created} baru, {updated} diperbarui." },
});

Object.assign(vi, {
  common: { home: "Trang chủ", dashboard: "Bảng điều khiển", how: "Cách hoạt động", examples: "Ví dụ", useCases: "Tình huống sử dụng", faq: "Hỏi đáp", menu: "Menu", signIn: "Đăng nhập", createAccount: "Tạo tài khoản", earlyAccess: "Yêu cầu truy cập", language: "Ngôn ngữ", backHome: "Về TRAPEAK", delete: "Xóa", unavailable: "Không khả dụng", notRecorded: "Chưa ghi nhận", readGuide: "Đọc hướng dẫn →", privateBeta: "Beta riêng tư", contact: "Liên hệ", legal: "Pháp lý", privacy: "Chính sách quyền riêng tư", terms: "Điều khoản dịch vụ", dataDeletion: "Xóa dữ liệu", copyright: "© 2026 TRAPEAK. Beta riêng tư." },
  nav: { overview: "Tổng quan", training: "Tập luyện", nutrition: "Dinh dưỡng", health: "Sức khỏe", sharedAccess: "Quyền truy cập chia sẻ", connections: "Kết nối", profile: "Hồ sơ & tùy chọn", accountData: "Dữ liệu tài khoản" },
  auth: { eyebrow: "TÀI KHOẢN TRAPEAK", signInTitle: "Chào mừng bạn trở lại.", signInDescription: "Đăng nhập để quản lý dữ liệu tập luyện và sức khỏe cá nhân.", signInSetup: "Quyền truy cập tài khoản đang được thiết lập. Vui lòng quay lại sau.", signUpTitle: "Tạo tài khoản.", signUpDescription: "Giữ mọi kết nối và bản ghi tách biệt, dưới quyền kiểm soát của bạn.", signUpSetup: "Tính năng đăng ký đang được thiết lập. Vui lòng quay lại sau." },
  profile: { eyebrow: "HỒ SƠ & TÙY CHỌN", title: "Giao diện và đơn vị của bạn.", intro: "Ngôn ngữ, múi giờ và hệ đo lường là các lựa chọn độc lập. Chúng không quyết định ngôn ngữ bạn dùng với AI.", interface: "GIAO DIỆN", interfaceHint: "Các tùy chọn chỉ ảnh hưởng cách hiển thị; dữ liệu vẫn có cấu trúc và trung lập về ngôn ngữ.", language: "Ngôn ngữ giao diện", timeZone: "Múi giờ", timeZoneHint: "Dùng tên IANA như Asia/Ho_Chi_Minh.", measurement: "Hệ đo lường", measurementHint: "Hệ mét dùng kilogram và kilomet; hệ Anh dùng pound và dặm.", metric: "Hệ mét", imperial: "Hệ Anh", save: "Lưu tùy chọn", saving: "Đang lưu…", saved: "Đã lưu tùy chọn.", error: "Không thể lưu tùy chọn.", independence: "CÀI ĐẶT ĐỘC LẬP", independenceText: "Đổi ngôn ngữ không làm thay đổi múi giờ, đơn vị, dữ liệu đã lưu hay ngôn ngữ của ChatGPT, Claude hoặc AI khác." },
  dashboard: { overview: "TỔNG QUAN", title: "Dữ liệu của bạn, được sắp xếp rõ ràng.", intro: "Xem ngữ cảnh mà AI—hoặc người bạn cho phép—có thể dùng. Bản ghi chi tiết vẫn nằm trong từng danh mục.", dataOverview: "Tổng quan dữ liệu", noWorkouts: "Chưa có buổi tập", workout: "Buổi tập", durationUnavailable: "không có thời lượng", connectWahoo: "Kết nối Wahoo để bắt đầu lịch sử tập luyện có cấu trúc.", activities7: "hoạt động trong 7 ngày", openTraining: "Mở tập luyện →", nutritionToday: "DINH DƯỠNG · HÔM NAY", nothingLogged: "Chưa ghi gì", recordFood: "Ghi món ăn bằng giọng nói hoặc văn bản qua AI đã kết nối.", openNutrition: "Mở dinh dưỡng →", noLabs: "Chưa có báo cáo xét nghiệm", healthSeparate: "Sức khỏe luôn tách biệt với quyền Tập luyện và Dinh dưỡng.", openHealth: "Mở sức khỏe →", profileContext: "NGỮ CẢNH HỒ SƠ", goalsContext: "Mục tiêu, giới hạn và sở thích giúp phân tích của AI phù hợp hơn.", updateWithAi: "Cập nhật qua AI đã kết nối", noGrants: "Chưa có quyền đang hoạt động", shareByEmail: "Chia sẻ danh mục đã chọn qua email và đặt thời hạn.", manageAccess: "Quản lý quyền →", noWearable: "Chưa có thiết bị", workoutsStored: "buổi tập đã lưu.", otherDataWithAi: "Dinh dưỡng, cân nặng, hồ sơ và xét nghiệm vẫn có thể lưu qua AI.", manageConnections: "Quản lý kết nối →", boundaries: "RANH GIỚI DỮ LIỆU", boundaryTitle: "Ba danh mục. Không có gói ẩn.", trainingDescription: "Buổi tập, tải tập, mục tiêu và giới hạn thực tế.", nutritionDescription: "Bữa ăn, macro, bối cảnh ăn uống và lịch sử cân nặng.", healthDescription: "Xét nghiệm, bệnh lý, chấn thương, chống chỉ định và thuốc." },
  training: { title: "Buổi tập và bối cảnh tải tập.", intro: "Các buổi đã hoàn thành, xu hướng gần đây và phạm vi nguồn. TRAPEAK cung cấp ngữ cảnh—không phải điểm sẵn sàng hay chỉ định tự động.", unavailable: "Dữ liệu tập luyện không khả dụng.", unavailableHint: "Kết nối Wahoo hoặc hoàn tất cấu hình lưu trữ rồi quay lại.", openConnections: "Mở kết nối", last7: "7 NGÀY QUA", trainingTime: "THỜI GIAN TẬP", previous7: "7 NGÀY TRƯỚC ĐÓ", consecutive: "NGÀY LIÊN TIẾP", activities: "hoạt động", days: "ngày tập", recent: "LỊCH SỬ GẦN ĐÂY", completed: "Buổi tập đã hoàn thành.", in28: "trong 28 ngày qua", noCompleted: "Không có buổi tập hoàn thành trong giai đoạn này.", activity: "Hoạt động", askAi: "HỎI AI", prompt: "So sánh hai tuần gần nhất và đề xuất mục tiêu cho buổi hôm nay. Trước tiên hãy hỏi tôi cảm thấy thế nào.", coverage: "PHẠM VI NGUỒN", limitations: "Giới hạn đã biết." },
  nutrition: { title: "Tổng theo ngày, chi tiết bữa ăn khi cần.", intro: "Bắt đầu với bức tranh theo ngày. Chỉ mở từng ngày khi cần chi tiết và giả định.", summary: "Tóm tắt dinh dưỡng", today: "HÔM NAY", kilocalories: "kilocalo", protein: "PROTEIN", carbohydrates: "CARBOHYDRATE", latestWeight: "CÂN NẶNG GẦN NHẤT", noMeasurement: "chưa đo", unavailable: "Kho lưu trữ dinh dưỡng không khả dụng.", unavailableHint: "Hoàn tất cấu hình cơ sở dữ liệu rồi quay lại.", history: "LỊCH SỬ", byDay: "Dinh dưỡng theo ngày.", recentEntries: "bản ghi gần đây", noRecords: "Chưa có bản ghi dinh dưỡng.", example: "Thử: “Lưu bữa sáng: trứng tráng, bơ và hai miếng bánh giòn.”", entries: "bản ghi", openDetails: "Mở chi tiết", estimated: "ước tính", assumptions: "Giả định", recordNaturally: "GHI MỘT CÁCH TỰ NHIÊN", recordHint: "Dùng giọng nói, văn bản hoặc ảnh trong AI bạn chọn. Yêu cầu AI nêu giả định trước khi lưu calo và macro ước tính.", confirmDelete: "Xóa vĩnh viễn bản ghi dinh dưỡng này?" },
  health: { title: "Ngữ cảnh nhạy cảm, luôn tách biệt.", intro: "Lịch sử xét nghiệm, bệnh lý, chấn thương, chống chỉ định và thuốc. Quyền Tập luyện không bao gồm Sức khỏe.", laboratory: "XÉT NGHIỆM", reports: "Báo cáo đã lưu.", unavailable: "Kho lưu trữ xét nghiệm không khả dụng.", noReports: "Chưa có báo cáo xét nghiệm.", saveHint: "Yêu cầu AI trích xuất chính xác giá trị, đơn vị và khoảng tham chiếu trước khi lưu.", collected: "lấy mẫu", results: "kết quả", conditions: "BỆNH LÝ", noConditions: "Chưa ghi nhận bệnh lý.", injuries: "CHẤN THƯƠNG", noInjuries: "Chưa ghi nhận chấn thương.", contraindications: "CHỐNG CHỈ ĐỊNH", noContraindications: "Chưa ghi nhận chống chỉ định.", medications: "THUỐC", noMedications: "Chưa ghi nhận thuốc.", detailsMissing: "Chưa ghi chi tiết", adviceTitle: "Không phải tư vấn y tế.", advice: "TRAPEAK lưu các dữ kiện và giá trị do người dùng cung cấp. AI có thể giúp sắp xếp câu hỏi nhưng không thay thế chuyên gia y tế có chuyên môn.", confirmDelete: "Xóa vĩnh viễn báo cáo xét nghiệm này và mọi kết quả đã lưu?" },
  connections: { title: "Nguồn dữ liệu của bạn.", intro: "Nguồn đã kết nối cung cấp dữ kiện có ngày. Số đo bị thiếu vẫn là thiếu—không bao giờ được thay bằng ước tính.", available: "ĐANG KHẢ DỤNG", connected: "ĐÃ KẾT NỐI", reconnect: "KẾT NỐI LẠI", notConnected: "CHƯA KẾT NỐI", connectedAs: "Đã kết nối dưới tên", storedWorkouts: "Buổi tập đã lưu", lastSync: "Đồng bộ lần cuối", automatic: "Cập nhật tự động", enabled: "Đã bật", manual: "Đồng bộ thủ công", notAvailable: "Không khả dụng", sync: "Đồng bộ dữ liệu Wahoo", disconnect: "Ngắt kết nối", expired: "Quyền Wahoo đã hết hạn. Kết nối lại để khôi phục đồng bộ.", import: "Nhập các buổi tập hoàn thành đã được cho phép vào lịch sử TRAPEAK cá nhân.", connect: "Kết nối Wahoo", storageMissing: "Chưa cấu hình kho lưu trữ tích hợp.", roadmap: "LỘ TRÌNH NGUỒN", planned: "Đã lên kế hoạch · chờ phê duyệt", noRecovery: "Chưa có nguồn được hỗ trợ" },
  access: { eyebrow: "QUYỀN TRUY CẬP CHIA SẺ", title: "Dữ liệu của bạn. Quyền của bạn.", intro: "Mời huấn luyện viên, bác sĩ, chuyên gia dinh dưỡng hoặc người khác qua email. Chọn danh mục, thời hạn và thu hồi bất cứ lúc nào.", newInvitation: "LỜI MỜI MỚI", chooseShare: "Chọn nội dung chia sẻ.", readonlyNotice: "Quyền chỉ đọc. Người nhận phải đăng nhập bằng đúng email trước khi chấp nhận.", rules: "QUY TẮC TRUY CẬP", rule1: "Tập luyện, Dinh dưỡng và Sức khỏe là ba danh mục độc lập.", rule2: "Không danh mục nào mở quyền cho danh mục khác.", rule3: "Mỗi lần đọc đều được kiểm tra với quyền đang hoạt động và ghi vào nhật ký kiểm toán.", outgoing: "ĐÃ GỬI", peopleAccess: "Người có quyền truy cập.", total: "tổng", none: "Chưa có lời mời.", incoming: "ĐÃ NHẬN", sharedWithYou: "Dữ liệu được chia sẻ với bạn.", active: "đang hoạt động", noneIncoming: "Chưa có quyền chia sẻ đang hoạt động.", sharedUser: "Người dùng TRAPEAK", expires: "hết hạn", activity: "Hoạt động truy cập", events: "sự kiện", noneEvents: "Chưa có hoạt động truy cập.", training: "Tập luyện", nutrition: "Dinh dưỡng", health: "Sức khỏe", recoveryLegacy: "Phục hồi (cũ)", email: "Email người nhận", categories: "Chọn danh mục dữ liệu", trainingDescription: "Buổi tập, tải tập, mục tiêu và giới hạn", nutritionDescription: "Bữa ăn, macro, bối cảnh ăn uống và cân nặng", healthDescription: "Xét nghiệm, bệnh lý, chấn thương và thuốc", recoveryDescription: "Dành cho khi có nguồn được hỗ trợ", healthWarning: "Sức khỏe bao gồm xét nghiệm, bệnh lý, chấn thương, chống chỉ định và thuốc.", period: "Thời hạn truy cập", days7: "7 ngày", days30: "30 ngày", days90: "90 ngày", year1: "1 năm", creating: "Đang tạo…", create: "Tạo lời mời", invitationError: "Không thể tạo lời mời truy cập.", invitationLink: "Liên kết lời mời", linkHint: "Chỉ gửi liên kết dùng một lần này đến email đã chỉ định.", revoking: "Đang thu hồi…", revoke: "Thu hồi", invitationEyebrow: "LỜI MỜI TRUY CẬP", invitationTitle: "Có người đã chia sẻ dữ liệu TRAPEAK với bạn.", invitationIntro: "Khi chấp nhận, lời mời được gắn với tài khoản của bạn. Quyền chỉ đọc, giới hạn theo danh mục và thời hạn, và chủ sở hữu có thể thu hồi.", accepting: "Đang chấp nhận…", accept: "Chấp nhận quyền chỉ đọc", rejecting: "Đang từ chối…", reject: "Từ chối", responseError: "Không thể lưu phản hồi." },
  status: { connected: "Đã kết nối Wahoo thành công.", disconnected: "Đã ngắt kết nối Wahoo.", denied: "Đã hủy ủy quyền Wahoo.", invalidState: "Yêu cầu kết nối đã hết hạn. Vui lòng thử lại.", alreadyLinked: "Tài khoản Wahoo này đã liên kết với một tài khoản TRAPEAK khác.", error: "Không thể kết nối Wahoo. Vui lòng thử lại.", disconnectError: "Không thể ngắt kết nối Wahoo.", notConnected: "Hãy kết nối Wahoo trước khi đồng bộ buổi tập.", reconnectRequired: "Quyền Wahoo đã hết hạn. Hãy kết nối lại để tiếp tục.", syncError: "Không thể đồng bộ dữ liệu Wahoo.", syncSuccess: "Đã đồng bộ Wahoo: nhận {received}, mới {created}, cập nhật {updated}." },
});

Object.assign(hi, {
  common: { home: "होम", dashboard: "डैशबोर्ड", how: "यह कैसे काम करता है", examples: "उदाहरण", useCases: "उपयोग", faq: "सवाल-जवाब", menu: "मेन्यू", signIn: "साइन इन", createAccount: "खाता बनाएँ", earlyAccess: "पहुँच माँगें", language: "भाषा", backHome: "TRAPEAK पर वापस", delete: "हटाएँ", unavailable: "उपलब्ध नहीं", notRecorded: "दर्ज नहीं", readGuide: "गाइड पढ़ें →", privateBeta: "निजी बीटा", contact: "संपर्क", legal: "कानूनी", privacy: "गोपनीयता नीति", terms: "सेवा की शर्तें", dataDeletion: "डेटा हटाना", copyright: "© 2026 TRAPEAK. निजी बीटा।" },
  nav: { overview: "सारांश", training: "ट्रेनिंग", nutrition: "पोषण", health: "स्वास्थ्य", sharedAccess: "साझा पहुँच", connections: "कनेक्शन", profile: "प्रोफ़ाइल और पसंद", accountData: "खाता डेटा" },
  auth: { eyebrow: "TRAPEAK खाता", signInTitle: "फिर से स्वागत है।", signInDescription: "अपना ट्रेनिंग और स्वास्थ्य डेटा सँभालने के लिए साइन इन करें।", signInSetup: "खाता पहुँच तैयार की जा रही है। कृपया बाद में देखें।", signUpTitle: "अपना खाता बनाएँ।", signUpDescription: "हर कनेक्शन और रिकॉर्ड को अलग और अपने नियंत्रण में रखें।", signUpSetup: "खाता पंजीकरण तैयार किया जा रहा है। कृपया बाद में देखें।" },
  profile: { eyebrow: "प्रोफ़ाइल और पसंद", title: "आपका इंटरफ़ेस, आपकी इकाइयाँ।", intro: "भाषा, समय क्षेत्र और माप प्रणाली अलग विकल्प हैं। इनमें से कोई भी AI से बातचीत की भाषा तय नहीं करता।", interface: "इंटरफ़ेस", interfaceHint: "ये विकल्प केवल प्रस्तुति बदलते हैं; संग्रहित डेटा संरचित और भाषा-निरपेक्ष रहता है।", language: "इंटरफ़ेस भाषा", timeZone: "समय क्षेत्र", timeZoneHint: "Asia/Kolkata जैसा IANA नाम उपयोग करें।", measurement: "माप प्रणाली", measurementHint: "मीट्रिक में किलोग्राम और किलोमीटर; इम्पीरियल में पाउंड और मील।", metric: "मीट्रिक", imperial: "इम्पीरियल", save: "पसंद सहेजें", saving: "सहेज रहे हैं…", saved: "पसंद सहेजी गई।", error: "पसंद सहेजी नहीं जा सकी।", independence: "स्वतंत्र सेटिंग्स", independenceText: "भाषा बदलने से समय क्षेत्र, इकाइयाँ, संग्रहित डेटा या ChatGPT, Claude और अन्य AI की भाषा नहीं बदलती।" },
  dashboard: { overview: "सारांश", title: "आपका डेटा, व्यवस्थित।", intro: "देखें कि AI—या आपकी अनुमति वाला व्यक्ति—कौन-सा संदर्भ इस्तेमाल कर सकता है। विस्तृत रिकॉर्ड अपनी श्रेणी में रहते हैं।", dataOverview: "डेटा सारांश", noWorkouts: "कोई वर्कआउट नहीं", workout: "वर्कआउट", durationUnavailable: "अवधि उपलब्ध नहीं", connectWahoo: "संरचित ट्रेनिंग इतिहास शुरू करने के लिए Wahoo जोड़ें।", activities7: "7 दिनों की गतिविधियाँ", openTraining: "ट्रेनिंग खोलें →", nutritionToday: "पोषण · आज", nothingLogged: "कुछ दर्ज नहीं", recordFood: "कनेक्टेड AI में आवाज़ या टेक्स्ट से भोजन दर्ज करें।", openNutrition: "पोषण खोलें →", noLabs: "कोई लैब रिपोर्ट नहीं", healthSeparate: "स्वास्थ्य का एक्सेस ट्रेनिंग और पोषण से अलग रहता है।", openHealth: "स्वास्थ्य खोलें →", profileContext: "प्रोफ़ाइल संदर्भ", goalsContext: "लक्ष्य, सीमाएँ और पसंद AI विश्लेषण को अधिक उपयोगी बनाते हैं।", updateWithAi: "कनेक्टेड AI से अपडेट करें", noGrants: "कोई सक्रिय अनुमति नहीं", shareByEmail: "चुनी श्रेणियाँ ईमेल से, समाप्ति तिथि के साथ साझा करें।", manageAccess: "एक्सेस सँभालें →", noWearable: "कोई डिवाइस नहीं", workoutsStored: "वर्कआउट सहेजे गए।", otherDataWithAi: "पोषण, वजन, प्रोफ़ाइल और लैब डेटा AI के जरिए भी सहेजा जा सकता है।", manageConnections: "कनेक्शन सँभालें →", boundaries: "डेटा सीमाएँ", boundaryTitle: "तीन श्रेणियाँ। कोई छिपा पैकेज नहीं।", trainingDescription: "वर्कआउट, ट्रेनिंग लोड, लक्ष्य और व्यावहारिक सीमाएँ।", nutritionDescription: "भोजन, मैक्रो, खान-पान संदर्भ और दिनांकित वजन।", healthDescription: "लैब परिणाम, स्थितियाँ, चोट, मतभेद और दवाएँ।" },
  training: { title: "वर्कआउट और लोड का संदर्भ।", intro: "पूरे हुए सत्र, हाल के पैटर्न और स्रोत कवरेज। TRAPEAK संदर्भ देता है—तैयारी स्कोर या स्वचालित प्रिस्क्रिप्शन नहीं।", unavailable: "ट्रेनिंग डेटा उपलब्ध नहीं है।", unavailableHint: "Wahoo जोड़ें या स्टोरेज सेटअप पूरा करें, फिर वापस आएँ।", openConnections: "कनेक्शन खोलें", last7: "पिछले 7 दिन", trainingTime: "ट्रेनिंग समय", previous7: "उससे पहले के 7 दिन", consecutive: "लगातार दिन", activities: "गतिविधियाँ", days: "ट्रेनिंग दिन", recent: "हाल का इतिहास", completed: "पूरे हुए वर्कआउट।", in28: "पिछले 28 दिनों में", noCompleted: "इस अवधि में कोई पूरा वर्कआउट नहीं है।", activity: "गतिविधि", askAi: "AI से पूछें", prompt: "मेरे पिछले दो सप्ताह की तुलना करें और आज के सत्र का उद्देश्य सुझाएँ। पहले पूछें कि मैं कैसा महसूस कर रहा हूँ।", coverage: "स्रोत कवरेज", limitations: "ज्ञात सीमाएँ।" },
  nutrition: { title: "रोज़ का कुल, जरूरत पर भोजन का विवरण।", intro: "पहले दिन का सार देखें। भोजन और अनुमानों का विवरण चाहिए तभी किसी दिन को खोलें।", summary: "पोषण सारांश", today: "आज", kilocalories: "किलोकैलरी", protein: "प्रोटीन", carbohydrates: "कार्बोहाइड्रेट", latestWeight: "नवीनतम वजन", noMeasurement: "कोई माप नहीं", unavailable: "पोषण स्टोरेज उपलब्ध नहीं है।", unavailableHint: "डेटाबेस स्टोरेज का सेटअप पूरा करें, फिर वापस आएँ।", history: "इतिहास", byDay: "दिन के अनुसार पोषण।", recentEntries: "हाल के रिकॉर्ड", noRecords: "अभी कोई पोषण रिकॉर्ड नहीं है।", example: "उदाहरण: “नाश्ता सहेजें: ऑमलेट, एवोकाडो और दो क्रिस्पब्रेड।”", entries: "रिकॉर्ड", openDetails: "विवरण खोलें", estimated: "अनुमानित", assumptions: "अनुमान", recordNaturally: "स्वाभाविक रूप से दर्ज करें", recordHint: "चुने हुए AI में आवाज़, टेक्स्ट या तस्वीर उपयोग करें। अनुमानित कैलरी और मैक्रो सहेजने से पहले सभी धारणाएँ बताने को कहें।", confirmDelete: "यह पोषण रिकॉर्ड हमेशा के लिए हटाएँ?" },
  health: { title: "संवेदनशील संदर्भ, हमेशा अलग।", intro: "लैब इतिहास, स्थितियाँ, चोट, मतभेद और दवाएँ। ट्रेनिंग एक्सेस से स्वास्थ्य एक्सेस कभी अपने आप नहीं मिलता।", laboratory: "लैब", reports: "सहेजी गई रिपोर्ट।", unavailable: "लैब स्टोरेज उपलब्ध नहीं है।", noReports: "कोई लैब रिपोर्ट सहेजी नहीं गई।", saveHint: "सहेजने से पहले AI से सटीक मान, इकाइयाँ और रेफरेंस रेंज निकालने को कहें।", collected: "नमूना तिथि", results: "परिणाम", conditions: "स्थितियाँ", noConditions: "कोई स्थिति दर्ज नहीं है।", injuries: "चोट", noInjuries: "कोई चोट दर्ज नहीं है।", contraindications: "मतभेद", noContraindications: "कोई मतभेद दर्ज नहीं है।", medications: "दवाएँ", noMedications: "कोई दवा दर्ज नहीं है।", detailsMissing: "विवरण दर्ज नहीं", adviceTitle: "यह चिकित्सा सलाह नहीं है।", advice: "TRAPEAK उपयोगकर्ता द्वारा दिए तथ्य और रिपोर्ट किए मान सहेजता है। AI सवाल व्यवस्थित करने में मदद कर सकता है, पर योग्य चिकित्सक की जगह नहीं ले सकता।", confirmDelete: "यह लैब रिपोर्ट और इसके सभी परिणाम हमेशा के लिए हटाएँ?" },
  connections: { title: "आपके स्रोत।", intro: "कनेक्टेड स्रोत दिनांकित तथ्य जोड़ते हैं। जो माप उपलब्ध नहीं हैं वे अनुपलब्ध ही रहते हैं—उनकी जगह अनुमान नहीं आता।", available: "अभी उपलब्ध", connected: "कनेक्टेड", reconnect: "फिर कनेक्ट करें", notConnected: "कनेक्टेड नहीं", connectedAs: "इस नाम से कनेक्टेड", storedWorkouts: "सहेजे वर्कआउट", lastSync: "आखिरी सिंक", automatic: "स्वचालित अपडेट", enabled: "चालू", manual: "मैनुअल सिंक", notAvailable: "उपलब्ध नहीं", sync: "Wahoo डेटा सिंक करें", disconnect: "डिस्कनेक्ट करें", expired: "Wahoo एक्सेस समाप्त हो गया। सिंक बहाल करने के लिए फिर कनेक्ट करें।", import: "अधिकृत पूरे वर्कआउट अपने निजी TRAPEAK इतिहास में आयात करें।", connect: "Wahoo जोड़ें", storageMissing: "इंटीग्रेशन स्टोरेज कॉन्फ़िगर नहीं है।", roadmap: "स्रोत रोडमैप", planned: "नियोजित · प्रदाता की मंजूरी लंबित", noRecovery: "अभी कोई समर्थित स्रोत नहीं" },
  access: { eyebrow: "साझा एक्सेस", title: "आपका डेटा। आपकी अनुमति।", intro: "कोच, डॉक्टर, डाइटीशियन या किसी अन्य व्यक्ति को ईमेल से बुलाएँ। श्रेणियाँ और समाप्ति चुनें, और कभी भी एक्सेस हटाएँ।", newInvitation: "नया आमंत्रण", chooseShare: "क्या साझा करना है चुनें।", readonlyNotice: "एक्सेस केवल पढ़ने का है। स्वीकार करने से पहले व्यक्ति को उसी ईमेल से साइन इन करना होगा।", rules: "एक्सेस नियम", rule1: "ट्रेनिंग, पोषण और स्वास्थ्य अलग श्रेणियाँ हैं।", rule2: "कोई श्रेणी दूसरी श्रेणी का एक्सेस नहीं देती।", rule3: "हर पढ़ने की क्रिया सक्रिय अनुमति से जाँची और ऑडिट रिकॉर्ड में लिखी जाती है।", outgoing: "भेजे गए", peopleAccess: "एक्सेस वाले लोग।", total: "कुल", none: "अभी कोई आमंत्रण नहीं।", incoming: "प्राप्त", sharedWithYou: "आपसे साझा डेटा।", active: "सक्रिय", noneIncoming: "कोई सक्रिय साझा एक्सेस नहीं।", sharedUser: "TRAPEAK उपयोगकर्ता", expires: "समाप्ति", activity: "एक्सेस गतिविधि", events: "घटनाएँ", noneEvents: "अभी कोई एक्सेस गतिविधि नहीं।", training: "ट्रेनिंग", nutrition: "पोषण", health: "स्वास्थ्य", recoveryLegacy: "रिकवरी (पुराना)", email: "व्यक्ति का ईमेल", categories: "डेटा श्रेणियाँ चुनें", trainingDescription: "वर्कआउट, लोड, लक्ष्य और ट्रेनिंग सीमाएँ", nutritionDescription: "भोजन, मैक्रो, खान-पान संदर्भ और दिनांकित वजन", healthDescription: "लैब, स्थितियाँ, चोट और दवाएँ", recoveryDescription: "समर्थित स्रोत उपलब्ध होने तक सुरक्षित", healthWarning: "स्वास्थ्य में लैब परिणाम, स्थितियाँ, चोट, मतभेद और दवाएँ शामिल हैं।", period: "एक्सेस अवधि", days7: "7 दिन", days30: "30 दिन", days90: "90 दिन", year1: "1 वर्ष", creating: "बना रहे हैं…", create: "आमंत्रण बनाएँ", invitationError: "एक्सेस आमंत्रण नहीं बन सका।", invitationLink: "आमंत्रण लिंक", linkHint: "यह एक बार उपयोग होने वाला लिंक केवल बताए ईमेल पर भेजें।", revoking: "हटा रहे हैं…", revoke: "एक्सेस हटाएँ", invitationEyebrow: "एक्सेस आमंत्रण", invitationTitle: "किसी ने आपके साथ TRAPEAK डेटा साझा किया है।", invitationIntro: "स्वीकार करने पर आमंत्रण आपके साइन-इन खाते से जुड़ता है। यह केवल पढ़ने, श्रेणी और समय तक सीमित है और मालिक इसे हटा सकता है।", accepting: "स्वीकार हो रहा है…", accept: "केवल-पढ़ने का एक्सेस स्वीकार करें", rejecting: "अस्वीकार हो रहा है…", reject: "अस्वीकार करें", responseError: "आमंत्रण का जवाब सहेजा नहीं जा सका।" },
  status: { connected: "Wahoo सफलतापूर्वक कनेक्ट हुआ।", disconnected: "Wahoo डिस्कनेक्ट हुआ।", denied: "Wahoo की अनुमति रद्द की गई।", invalidState: "कनेक्शन अनुरोध समाप्त हो गया। फिर प्रयास करें।", alreadyLinked: "यह Wahoo खाता पहले से दूसरे TRAPEAK खाते से जुड़ा है।", error: "Wahoo कनेक्ट नहीं हो सका। फिर प्रयास करें।", disconnectError: "Wahoo डिस्कनेक्ट नहीं हो सका।", notConnected: "वर्कआउट सिंक करने से पहले Wahoo जोड़ें।", reconnectRequired: "Wahoo एक्सेस समाप्त हो गया। जारी रखने के लिए फिर जोड़ें।", syncError: "Wahoo डेटा सिंक नहीं हो सका।", syncSuccess: "Wahoo सिंक हुआ: {received} मिले, {created} नए, {updated} अपडेट हुए।" },
});

Object.assign(bn, {
  common: { home: "হোম", dashboard: "ড্যাশবোর্ড", how: "যেভাবে কাজ করে", examples: "উদাহরণ", useCases: "ব্যবহারের ক্ষেত্র", faq: "প্রশ্নোত্তর", menu: "মেনু", signIn: "সাইন ইন", createAccount: "অ্যাকাউন্ট তৈরি করুন", earlyAccess: "অ্যাক্সেস চান", language: "ভাষা", backHome: "TRAPEAK-এ ফিরুন", delete: "মুছুন", unavailable: "উপলভ্য নয়", notRecorded: "রেকর্ড করা হয়নি", readGuide: "গাইড পড়ুন →", privateBeta: "প্রাইভেট বেটা", contact: "যোগাযোগ", legal: "আইনি", privacy: "গোপনীয়তা নীতি", terms: "সেবার শর্তাবলি", dataDeletion: "ডেটা মুছে ফেলা", copyright: "© 2026 TRAPEAK. প্রাইভেট বেটা।" },
  nav: { overview: "সারসংক্ষেপ", training: "ট্রেনিং", nutrition: "পুষ্টি", health: "স্বাস্থ্য", sharedAccess: "শেয়ার করা অ্যাক্সেস", connections: "সংযোগ", profile: "প্রোফাইল ও পছন্দ", accountData: "অ্যাকাউন্ট ডেটা" },
  auth: { eyebrow: "TRAPEAK অ্যাকাউন্ট", signInTitle: "আবার স্বাগতম।", signInDescription: "আপনার ট্রেনিং ও স্বাস্থ্য ডেটা পরিচালনা করতে সাইন ইন করুন।", signInSetup: "অ্যাকাউন্ট অ্যাক্সেস প্রস্তুত করা হচ্ছে। পরে আবার দেখুন।", signUpTitle: "আপনার অ্যাকাউন্ট তৈরি করুন।", signUpDescription: "প্রতিটি সংযোগ ও রেকর্ড আলাদা এবং আপনার নিয়ন্ত্রণে রাখুন।", signUpSetup: "অ্যাকাউন্ট নিবন্ধন প্রস্তুত করা হচ্ছে। পরে আবার দেখুন।" },
  profile: { eyebrow: "প্রোফাইল ও পছন্দ", title: "আপনার ইন্টারফেস, আপনার একক।", intro: "ভাষা, সময় অঞ্চল ও পরিমাপ পদ্ধতি আলাদা পছন্দ। এগুলো AI-এর সঙ্গে আপনার কথার ভাষা ঠিক করে না।", interface: "ইন্টারফেস", interfaceHint: "এই পছন্দগুলো শুধু উপস্থাপন বদলায়; সংরক্ষিত ডেটা কাঠামোবদ্ধ ও ভাষা-নিরপেক্ষ থাকে।", language: "ইন্টারফেসের ভাষা", timeZone: "সময় অঞ্চল", timeZoneHint: "Asia/Dhaka-এর মতো IANA নাম ব্যবহার করুন।", measurement: "পরিমাপ পদ্ধতি", measurementHint: "মেট্রিকে কিলোগ্রাম ও কিলোমিটার; ইম্পেরিয়ালে পাউন্ড ও মাইল।", metric: "মেট্রিক", imperial: "ইম্পেরিয়াল", save: "পছন্দ সংরক্ষণ করুন", saving: "সংরক্ষণ হচ্ছে…", saved: "পছন্দ সংরক্ষিত হয়েছে।", error: "পছন্দ সংরক্ষণ করা যায়নি।", independence: "স্বাধীন সেটিংস", independenceText: "ভাষা বদলালে সময় অঞ্চল, একক, সংরক্ষিত ডেটা বা ChatGPT, Claude ও অন্য AI-এর ভাষা বদলায় না।" },
  dashboard: { overview: "সারসংক্ষেপ", title: "আপনার ডেটা, গুছিয়ে রাখা।", intro: "AI—বা আপনার অনুমতি দেওয়া ব্যক্তি—কোন প্রসঙ্গ ব্যবহার করতে পারেন তা দেখুন। বিস্তারিত রেকর্ড নিজ নিজ বিভাগে থাকে।", dataOverview: "ডেটার সারসংক্ষেপ", noWorkouts: "কোনো ওয়ার্কআউট নেই", workout: "ওয়ার্কআউট", durationUnavailable: "সময়কাল নেই", connectWahoo: "কাঠামোবদ্ধ ট্রেনিং ইতিহাস শুরু করতে Wahoo যুক্ত করুন।", activities7: "৭ দিনে কার্যক্রম", openTraining: "ট্রেনিং খুলুন →", nutritionToday: "পুষ্টি · আজ", nothingLogged: "কিছু রেকর্ড হয়নি", recordFood: "সংযুক্ত AI-এ ভয়েস বা টেক্সটে খাবার রেকর্ড করুন।", openNutrition: "পুষ্টি খুলুন →", noLabs: "কোনো ল্যাব রিপোর্ট নেই", healthSeparate: "স্বাস্থ্য অ্যাক্সেস ট্রেনিং ও পুষ্টি থেকে আলাদা থাকে।", openHealth: "স্বাস্থ্য খুলুন →", profileContext: "প্রোফাইল প্রসঙ্গ", goalsContext: "লক্ষ্য, সীমা ও পছন্দ AI বিশ্লেষণকে আরও প্রাসঙ্গিক করে।", updateWithAi: "সংযুক্ত AI দিয়ে আপডেট করুন", noGrants: "কোনো সক্রিয় অনুমতি নেই", shareByEmail: "নির্বাচিত বিভাগ মেয়াদসহ ইমেইলে শেয়ার করুন।", manageAccess: "অ্যাক্সেস পরিচালনা করুন →", noWearable: "কোনো ডিভাইস নেই", workoutsStored: "ওয়ার্কআউট সংরক্ষিত।", otherDataWithAi: "পুষ্টি, ওজন, প্রোফাইল ও ল্যাব ডেটা AI দিয়েও সংরক্ষণ করা যায়।", manageConnections: "সংযোগ পরিচালনা করুন →", boundaries: "ডেটার সীমা", boundaryTitle: "তিনটি বিভাগ। কোনো গোপন প্যাকেজ নেই।", trainingDescription: "ওয়ার্কআউট, ট্রেনিং লোড, লক্ষ্য ও বাস্তব সীমা।", nutritionDescription: "খাবার, ম্যাক্রো, খাদ্য প্রসঙ্গ ও তারিখসহ ওজন।", healthDescription: "ল্যাব ফল, অবস্থা, আঘাত, contraindication ও ওষুধ।" },
  training: { title: "ওয়ার্কআউট ও লোডের প্রসঙ্গ।", intro: "সম্পন্ন সেশন, সাম্প্রতিক ধারা ও উৎসের পরিধি। TRAPEAK প্রসঙ্গ দেয়—স্বয়ংক্রিয় প্রস্তুতি স্কোর বা প্রেসক্রিপশন নয়।", unavailable: "ট্রেনিং ডেটা পাওয়া যাচ্ছে না।", unavailableHint: "Wahoo যুক্ত করুন বা স্টোরেজ সেটআপ শেষ করে ফিরে আসুন।", openConnections: "সংযোগ খুলুন", last7: "গত ৭ দিন", trainingTime: "ট্রেনিং সময়", previous7: "আগের ৭ দিন", consecutive: "টানা দিন", activities: "কার্যক্রম", days: "ট্রেনিং দিন", recent: "সাম্প্রতিক ইতিহাস", completed: "সম্পন্ন ওয়ার্কআউট।", in28: "গত ২৮ দিনে", noCompleted: "এই সময়ে কোনো সম্পন্ন ওয়ার্কআউট নেই।", activity: "কার্যক্রম", askAi: "AI-কে জিজ্ঞেস করুন", prompt: "আমার গত দুই সপ্তাহ তুলনা করে আজকের সেশনের উদ্দেশ্য বলুন। আগে জিজ্ঞেস করুন আজ আমি কেমন আছি।", coverage: "উৎসের পরিধি", limitations: "জানা সীমাবদ্ধতা।" },
  nutrition: { title: "দৈনিক মোট, প্রয়োজনে খাবারের বিস্তারিত।", intro: "প্রথমে দিনের সারাংশ দেখুন। খাবারের বিস্তারিত ও অনুমান দরকার হলেই দিনটি খুলুন।", summary: "পুষ্টির সারাংশ", today: "আজ", kilocalories: "কিলোক্যালরি", protein: "প্রোটিন", carbohydrates: "কার্বোহাইড্রেট", latestWeight: "সর্বশেষ ওজন", noMeasurement: "কোনো মাপ নেই", unavailable: "পুষ্টির স্টোরেজ পাওয়া যাচ্ছে না।", unavailableHint: "ডেটাবেস স্টোরেজ সেটআপ শেষ করে ফিরে আসুন।", history: "ইতিহাস", byDay: "দিন অনুযায়ী পুষ্টি।", recentEntries: "সাম্প্রতিক রেকর্ড", noRecords: "এখনও কোনো পুষ্টি রেকর্ড নেই।", example: "উদাহরণ: “সকালের খাবার সংরক্ষণ করুন: অমলেট, অ্যাভোকাডো ও দুইটি ক্রিস্পব্রেড।”", entries: "রেকর্ড", openDetails: "বিস্তারিত খুলুন", estimated: "আনুমানিক", assumptions: "অনুমান", recordNaturally: "স্বাভাবিকভাবে রেকর্ড করুন", recordHint: "পছন্দের AI-এ ভয়েস, টেক্সট বা ছবি ব্যবহার করুন। আনুমানিক ক্যালরি ও ম্যাক্রো সংরক্ষণের আগে সব অনুমান বলতে বলুন।", confirmDelete: "এই পুষ্টি রেকর্ড স্থায়ীভাবে মুছবেন?" },
  health: { title: "সংবেদনশীল প্রসঙ্গ, আলাদাভাবে রাখা।", intro: "ল্যাব ইতিহাস, অবস্থা, আঘাত, contraindication ও ওষুধ। ট্রেনিং অ্যাক্সেস কখনো নিজে থেকে স্বাস্থ্য অ্যাক্সেস দেয় না।", laboratory: "ল্যাবরেটরি", reports: "সংরক্ষিত রিপোর্ট।", unavailable: "ল্যাব স্টোরেজ পাওয়া যাচ্ছে না।", noReports: "কোনো ল্যাব রিপোর্ট সংরক্ষিত নেই।", saveHint: "সংরক্ষণের আগে AI-কে সঠিক মান, একক ও reference range বের করতে বলুন।", collected: "নমুনার তারিখ", results: "ফলাফল", conditions: "অবস্থা", noConditions: "কোনো অবস্থা রেকর্ড নেই।", injuries: "আঘাত", noInjuries: "কোনো আঘাত রেকর্ড নেই।", contraindications: "CONTRAINDICATION", noContraindications: "কোনো contraindication রেকর্ড নেই।", medications: "ওষুধ", noMedications: "কোনো ওষুধ রেকর্ড নেই।", detailsMissing: "বিস্তারিত রেকর্ড নেই", adviceTitle: "এটি চিকিৎসা পরামর্শ নয়।", advice: "TRAPEAK ব্যবহারকারীর দেওয়া তথ্য ও রিপোর্ট করা মান সংরক্ষণ করে। AI প্রশ্ন গুছিয়ে দিতে পারে, কিন্তু যোগ্য চিকিৎসকের বিকল্প নয়।", confirmDelete: "এই ল্যাব রিপোর্ট ও সব ফলাফল স্থায়ীভাবে মুছবেন?" },
  connections: { title: "আপনার উৎস।", intro: "সংযুক্ত উৎস তারিখসহ তথ্য যোগ করে। অনুপস্থিত মাপ অনুপস্থিতই থাকে—অনুমান দিয়ে পূরণ করা হয় না।", available: "এখন উপলভ্য", connected: "সংযুক্ত", reconnect: "আবার সংযুক্ত করুন", notConnected: "সংযুক্ত নয়", connectedAs: "এই নামে সংযুক্ত", storedWorkouts: "সংরক্ষিত ওয়ার্কআউট", lastSync: "সর্বশেষ সিঙ্ক", automatic: "স্বয়ংক্রিয় আপডেট", enabled: "চালু", manual: "ম্যানুয়াল সিঙ্ক", notAvailable: "উপলভ্য নয়", sync: "Wahoo ডেটা সিঙ্ক করুন", disconnect: "সংযোগ বিচ্ছিন্ন করুন", expired: "Wahoo অ্যাক্সেসের মেয়াদ শেষ। সিঙ্ক ফেরাতে আবার সংযুক্ত করুন।", import: "অনুমোদিত সম্পন্ন ওয়ার্কআউট ব্যক্তিগত TRAPEAK ইতিহাসে আমদানি করুন।", connect: "Wahoo যুক্ত করুন", storageMissing: "ইন্টিগ্রেশন স্টোরেজ কনফিগার করা নেই।", roadmap: "উৎসের রোডম্যাপ", planned: "পরিকল্পিত · প্রদানকারীর অনুমোদন বাকি", noRecovery: "এখনও কোনো সমর্থিত উৎস নেই" },
  access: { eyebrow: "শেয়ার করা অ্যাক্সেস", title: "আপনার ডেটা। আপনার অনুমতি।", intro: "কোচ, ডাক্তার, ডায়েটিশিয়ান বা অন্য কাউকে ইমেইলে আমন্ত্রণ জানান। বিভাগ ও মেয়াদ বাছুন, এবং যেকোনো সময় অ্যাক্সেস বাতিল করুন।", newInvitation: "নতুন আমন্ত্রণ", chooseShare: "কী শেয়ার করবেন বাছুন।", readonlyNotice: "অ্যাক্সেস শুধু পড়ার জন্য। গ্রহণের আগে প্রাপককে একই ইমেইলে সাইন ইন করতে হবে।", rules: "অ্যাক্সেসের নিয়ম", rule1: "ট্রেনিং, পুষ্টি ও স্বাস্থ্য আলাদা বিভাগ।", rule2: "এক বিভাগ অন্য বিভাগের অ্যাক্সেস দেয় না।", rule3: "প্রতিবার পড়ার আগে সক্রিয় অনুমতি যাচাই হয় এবং audit trail-এ লেখা হয়।", outgoing: "পাঠানো", peopleAccess: "অ্যাক্সেস থাকা ব্যক্তি।", total: "মোট", none: "এখনও কোনো আমন্ত্রণ নেই।", incoming: "পাওয়া", sharedWithYou: "আপনার সঙ্গে শেয়ার করা ডেটা।", active: "সক্রিয়", noneIncoming: "কোনো সক্রিয় শেয়ার করা অ্যাক্সেস নেই।", sharedUser: "TRAPEAK ব্যবহারকারী", expires: "মেয়াদ", activity: "অ্যাক্সেস কার্যক্রম", events: "ঘটনা", noneEvents: "এখনও কোনো অ্যাক্সেস কার্যক্রম নেই।", training: "ট্রেনিং", nutrition: "পুষ্টি", health: "স্বাস্থ্য", recoveryLegacy: "রিকভারি (পুরোনো)", email: "ব্যক্তির ইমেইল", categories: "ডেটার বিভাগ বাছুন", trainingDescription: "ওয়ার্কআউট, লোড, লক্ষ্য ও ট্রেনিং সীমা", nutritionDescription: "খাবার, ম্যাক্রো, খাদ্য প্রসঙ্গ ও তারিখসহ ওজন", healthDescription: "ল্যাব, অবস্থা, আঘাত ও ওষুধ", recoveryDescription: "সমর্থিত উৎস না আসা পর্যন্ত সংরক্ষিত", healthWarning: "স্বাস্থ্য বিভাগে ল্যাব ফল, অবস্থা, আঘাত, contraindication ও ওষুধ রয়েছে।", period: "অ্যাক্সেসের সময়কাল", days7: "৭ দিন", days30: "৩০ দিন", days90: "৯০ দিন", year1: "১ বছর", creating: "তৈরি হচ্ছে…", create: "আমন্ত্রণ তৈরি করুন", invitationError: "অ্যাক্সেসের আমন্ত্রণ তৈরি করা যায়নি।", invitationLink: "আমন্ত্রণের লিংক", linkHint: "একবার ব্যবহারযোগ্য এই লিংক শুধু নির্দিষ্ট ইমেইলে পাঠান।", revoking: "বাতিল হচ্ছে…", revoke: "বাতিল করুন", invitationEyebrow: "অ্যাক্সেস আমন্ত্রণ", invitationTitle: "কেউ আপনার সঙ্গে TRAPEAK ডেটা শেয়ার করেছেন।", invitationIntro: "গ্রহণ করলে আমন্ত্রণ আপনার সাইন-ইন অ্যাকাউন্টে যুক্ত হবে। এটি শুধু পড়া, বিভাগ ও মেয়াদে সীমিত এবং মালিক বাতিল করতে পারেন।", accepting: "গ্রহণ হচ্ছে…", accept: "শুধু-পড়ার অ্যাক্সেস গ্রহণ করুন", rejecting: "প্রত্যাখ্যান হচ্ছে…", reject: "প্রত্যাখ্যান করুন", responseError: "আমন্ত্রণের উত্তর সংরক্ষণ করা যায়নি।" },
  status: { connected: "Wahoo সফলভাবে সংযুক্ত হয়েছে।", disconnected: "Wahoo সংযোগ বিচ্ছিন্ন হয়েছে।", denied: "Wahoo অনুমোদন বাতিল হয়েছে।", invalidState: "সংযোগ অনুরোধের মেয়াদ শেষ। আবার চেষ্টা করুন।", alreadyLinked: "এই Wahoo অ্যাকাউন্ট অন্য TRAPEAK অ্যাকাউন্টে যুক্ত আছে।", error: "Wahoo সংযুক্ত করা যায়নি। আবার চেষ্টা করুন।", disconnectError: "Wahoo সংযোগ বিচ্ছিন্ন করা যায়নি।", notConnected: "ওয়ার্কআউট সিঙ্ক করার আগে Wahoo যুক্ত করুন।", reconnectRequired: "Wahoo অ্যাক্সেসের মেয়াদ শেষ। চালিয়ে যেতে আবার যুক্ত করুন।", syncError: "Wahoo ডেটা সিঙ্ক করা যায়নি।", syncSuccess: "Wahoo সিঙ্ক হয়েছে: {received} পাওয়া, {created} নতুন, {updated} আপডেট।" },
});

export const uiMessages: Readonly<Record<AppLocale, UiMessages>> = {
  en,
  "pt-BR": ptBR,
  "es-419": es419,
  id,
  vi,
  hi,
  bn,
};

export function getUiMessages(locale: AppLocale): UiMessages {
  return uiMessages[locale];
}

export function interpolate(message: string, values: Readonly<Record<string, string | number>>): string {
  return message.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`));
}
